// `cospec init [path]` (DESIGN §2.1). Detects the repo state (A fresh / B
// existing-no-openspec / C existing-openspec), scaffolds `openspec/`, composes
// and writes the 11 schemas + harness files through the shared managed-file
// engine (update.ts / §6.5), writes `config.yaml` only when absent, optionally
// scaffolds the commit gate (§7), additively merges Claude permissions (§6.4),
// detects/removes leftover opsx files (§6.6), and prints the receipt. Every
// write is idempotent: a second `init` returns `unchanged` for every file and
// leaves the tree clean.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

import { canonFile } from '../canon/embedded.ts'
import type { CommandContext } from '../cli.ts'
import { openspecDir } from '../core/change.ts'
import { splitFrontmatter, type WriteResult } from '../core/managed-files.ts'
import { mergeMiseToml, type MiseMergeResult } from '../harness/mise-merge.ts'
import { type HarnessName, HARNESS_NAMES, isHarnessName } from '../harness/render.ts'
import {
  COSPEC_PERMISSION,
  mergeClaudeSettings,
  type SettingsMergeResult,
} from '../harness/settings-merge.ts'
import { generate } from './update.ts'

// --- repo state -------------------------------------------------------------

type RepoState = 'A' | 'B' | 'C'

function detectState(cwd: string): RepoState {
  if (existsSync(openspecDir(cwd))) return 'C'
  if (existsSync(join(cwd, 'package.json'))) return 'B'
  return 'A'
}

// --- harness selection ------------------------------------------------------

interface HarnessSelection {
  harnesses: HarnessName[]
  /** Non-null when the default was auto-applied (printed as a note). */
  note?: string
  /** Set when selection is impossible; caller exits 1. */
  error?: string
}

function parseHarnessArg(value: string): HarnessName[] | undefined {
  if (value === 'all') return [...HARNESS_NAMES]
  if (value === 'none') return []
  const names = value
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
  const out: HarnessName[] = []
  for (const name of names) {
    if (!isHarnessName(name)) return undefined
    if (!out.includes(name)) out.push(name)
  }
  return out
}

const VALID_HARNESS_MSG =
  'valid values: claude, codex, opencode, all, none (comma-separate for multiple, e.g. --harness claude,codex)'

function selectHarnesses(cwd: string, state: RepoState, arg: string | undefined): HarnessSelection {
  if (arg !== undefined) {
    const parsed = parseHarnessArg(arg)
    if (parsed === undefined)
      return { harnesses: [], error: `invalid --harness '${arg}'; ${VALID_HARNESS_MSG}` }
    return { harnesses: parsed }
  }
  const detected = HARNESS_NAMES.filter((h) => existsSync(join(cwd, `.${h}`)))
  if (detected.length > 0) return { harnesses: detected }
  if (state === 'A') {
    return { harnesses: ['claude'], note: 'No harness detected; defaulting to claude.' }
  }
  return {
    harnesses: [],
    error: `no harness detected and no --harness given; ${VALID_HARNESS_MSG}`,
  }
}

// --- config.yaml ------------------------------------------------------------

const CONFIG_YAML = `# openspec project config — owned by you, never regenerated by cospec.
# 'schema' is the default change type. Change types are conventional-commit types;
# create a change with 'cospec new <type> <slug>'.
schema: feat

# context: injected into every artifact's authoring instructions.
# context: |
#   One or two sentences of project-wide context for the agent.

# rules: extra per-artifact constraints, keyed by artifact id (repo-wide, not per-type).
# rules:
#   proposal:
#     - Keep the proposal focused on a single capability.
`

// --- gate scaffolding (§7) --------------------------------------------------

interface GateTarget {
  file: string
  tpl: string
}

// Whole-file configs with no additive-merge story: write if absent, else print
// the paste-ready snippet. mise.toml is handled separately — it is additively
// merged into an existing file (see mise-merge.ts).
const GATE_TARGETS: GateTarget[] = [
  { file: 'commitlint.config.mjs', tpl: 'commitlint.config.mjs.tpl' },
  { file: 'hk.pkl', tpl: 'hk.pkl.tpl' },
]

interface GateResult {
  /** Files created fresh (incl. mise.toml when it was absent). */
  written: string[]
  /** hk.pkl / commitlint (whole-file) → paste-ready snippet when already present. */
  snippets: { file: string; content: string }[]
  /** The mise.toml merge outcome, present only when a mise.toml already existed. */
  mise?: MiseMergeResult
}

function scaffoldGate(cwd: string): GateResult {
  const written: string[] = []
  const snippets: { file: string; content: string }[] = []
  for (const target of GATE_TARGETS) {
    // Resolve through the embedded registry, not join(import.meta.dir, ...):
    // the compiled standalone binary has no canon/ dir on disk, so a path-based
    // read ENOENTs there (the exact bug the embedded registry exists to fix).
    const content = readFileSync(canonFile(`gate/${target.tpl}`), 'utf8')
    const dest = join(cwd, target.file)
    if (existsSync(dest)) {
      snippets.push({ file: target.file, content })
    } else {
      writeFileSync(dest, content)
      written.push(target.file)
    }
  }

  // mise.toml: additively merge the template into an existing file. The
  // documented install flow ("add cospec to mise.toml, then cospec init") means
  // a mise.toml almost always exists, so write-if-absent alone left the gate
  // useless. Only write when the merge produced new content.
  const template = readFileSync(canonFile('gate/mise.toml.tpl'), 'utf8')
  const misePath = join(cwd, 'mise.toml')
  let mise: MiseMergeResult | undefined
  if (existsSync(misePath)) {
    mise = mergeMiseToml(readFileSync(misePath, 'utf8'), template)
    if (mise.content !== undefined) writeFileSync(misePath, mise.content)
  } else {
    writeFileSync(misePath, template)
    written.push('mise.toml')
  }

  return { written, snippets, mise }
}

// --- opsx detection / removal (§6.6) ----------------------------------------

/** A leftover openspec-generated ("opsx") file — never something cospec authored. */
interface OpsxFile {
  relpath: string
}

// Provenance-only: a file is opsx only when its own frontmatter proves openspec
// authored it (DESIGN §2.1/§6.6 — "user-authored files (no generatedBy) never
// touched"). Path/name conventions alone are NOT provenance: a plain
// `.opencode/commands/opsx/notes.md` or `opsx-helper.md` a user wrote by hand
// carries no marker and must never be deleted.
function isOpsxMarkdown(text: string): boolean {
  const { frontmatter } = splitFrontmatter(text)
  const meta = frontmatter?.metadata
  if (meta !== null && typeof meta === 'object') {
    const record = meta as Record<string, unknown>
    if (record.author === 'cospec') return false
    const gen = typeof record.generatedBy === 'string' ? record.generatedBy : ''
    // Skill files (SKILL.md) carry `metadata.author: openspec` + a bare-semver
    // `generatedBy` (e.g. 1.3.1, 1.5.0). cospec stamps its own files with
    // `author: cospec` (handled above) and a `cospec@x.y.z` tag, never a bare
    // semver, so any bare semver under an openspec author is a leftover opsx
    // file to clean up — matched by shape, not by a specific version.
    if (record.author === 'openspec' && /^\d+\.\d+\.\d+/.test(gen)) return true
  }
  // Command files (e.g. `.claude/commands/opsx/*.md`) carry `name: 'OPSX: …'`.
  const name = frontmatter?.name
  if (typeof name === 'string' && /^"?OPSX:/.test(name)) return true
  return false
}

function findOpsxFiles(cwd: string): OpsxFile[] {
  const out: OpsxFile[] = []
  const walk = (rel: string): void => {
    const abs = join(cwd, rel)
    if (!existsSync(abs)) return
    for (const entry of readdirSync(abs, { withFileTypes: true })) {
      const childRel = `${rel}/${entry.name}`
      if (entry.isDirectory()) walk(childRel)
      else if (entry.isFile() && entry.name.endsWith('.md')) {
        if (isOpsxMarkdown(readFileSync(join(cwd, childRel), 'utf8'))) {
          out.push({ relpath: childRel })
        }
      }
    }
  }
  for (const h of HARNESS_NAMES) walk(`.${h}`)
  return out.toSorted((a, b) => a.relpath.localeCompare(b.relpath))
}

function removeOpsxFiles(cwd: string, files: OpsxFile[]): void {
  const dirs = new Set<string>()
  for (const f of files) {
    const abs = join(cwd, f.relpath)
    if (existsSync(abs)) rmSync(abs)
    dirs.add(join(abs, '..'))
  }
  // Prune now-empty containing dirs (openspec-* skill dirs, opsx command dir).
  for (const dir of dirs) {
    if (existsSync(dir) && readdirSync(dir).length === 0) rmSync(dir, { recursive: true })
  }
}

// --- receipt ----------------------------------------------------------------

const RESTART_LINES: Record<HarnessName, string> = {
  claude: 'Restart Claude Code to pick up /cospec commands.',
  opencode: 'OpenCode: reload the project to pick up /cospec- commands.',
  codex:
    'Codex: skills load per-session; .codex/rules/cospec.rules pre-approves read-only cospec calls. No [features] hooks needed — cospec ships no hooks.',
}

// --- command entrypoint -----------------------------------------------------

export function run(ctx: CommandContext): number {
  const target = resolveTarget(ctx)
  const args = ctx.args
  const flags = ctx.flags
  const yes = args.includes('--yes')
  const force = args.includes('--force')
  const removeOpsx = args.includes('--remove-opsx')
  const harnessArg = argValue(args, '--harness')

  const state = detectState(target)
  const gateEnabled = args.includes('--gate')
    ? true
    : args.includes('--no-gate')
      ? false
      : state === 'A'

  const notGitTree = !existsSync(join(target, '.git'))

  const selection = selectHarnesses(target, state, harnessArg)
  if (selection.error !== undefined) {
    process.stderr.write(`cospec: ${selection.error}\n`)
    return 1
  }
  const { harnesses } = selection

  // Scaffold the tree.
  mkdirSync(join(target, 'openspec', 'specs'), { recursive: true })
  mkdirSync(join(target, 'openspec', 'changes', 'archive'), { recursive: true })

  // Schemas + harness files + manifest.
  const { results } = generate(target, { harnesses, force })

  // config.yaml — only if absent (never modified once present).
  const configPath = join(target, 'openspec', 'config.yaml')
  let configWritten = false
  if (!existsSync(configPath)) {
    writeFileSync(configPath, CONFIG_YAML)
    configWritten = true
  }

  // Gate.
  const gate = gateEnabled ? scaffoldGate(target) : undefined

  // Claude settings merge.
  let settings: SettingsMergeResult | undefined
  if (harnesses.includes('claude')) {
    const settingsPath = join(target, '.claude', 'settings.json')
    settings = mergeClaudeSettings(
      existsSync(settingsPath) ? readFileSync(settingsPath, 'utf8') : null,
    )
    if (settings.content !== undefined && settings.status !== 'unchanged') {
      mkdirSync(join(target, '.claude'), { recursive: true })
      writeFileSync(settingsPath, settings.content)
    }
  }

  // Opsx detection / removal.
  const opsx = findOpsxFiles(target)
  const opsxRemoved = opsx.length > 0 && (removeOpsx || yes)
  if (opsxRemoved) removeOpsxFiles(target, opsx)

  if (flags.json) {
    process.stdout.write(
      `${JSON.stringify(
        {
          version: 1,
          path: target,
          state,
          harnesses,
          gate: gate
            ? {
                written: gate.written,
                snippets: gate.snippets.map((s) => s.file),
                mise: gate.mise
                  ? {
                      status: gate.mise.status,
                      added: gate.mise.added,
                      conflicts: gate.mise.conflicts,
                    }
                  : null,
              }
            : null,
          config: { written: configWritten },
          settings: settings ? { status: settings.status, added: settings.added } : null,
          opsx: { found: opsx.map((o) => o.relpath), removed: opsxRemoved },
          notGitTree,
          files: results,
        },
        null,
        2,
      )}\n`,
    )
    return 0
  }

  printReceipt(target, {
    state,
    harnesses,
    results,
    configWritten,
    gate,
    settings,
    opsx,
    opsxRemoved,
    notGitTree,
    autoNote: selection.note,
  })
  return 0
}

/** The positional [path], skipping value-bearing flags (`--harness <v>`). */
function resolveTarget(ctx: CommandContext): string {
  const args = ctx.args
  for (let i = 0; i < args.length; i++) {
    const tok = args[i]!
    if (tok === '--harness') {
      i++ // consume its value
      continue
    }
    if (tok.startsWith('-')) continue
    return resolve(ctx.cwd, tok)
  }
  return ctx.cwd
}

function argValue(args: string[], flag: string): string | undefined {
  const idx = args.indexOf(flag)
  if (idx >= 0 && idx + 1 < args.length) {
    const next = args[idx + 1]!
    if (!next.startsWith('-')) return next
  }
  const eq = args.find((a) => a.startsWith(`${flag}=`))
  return eq?.slice(flag.length + 1)
}

interface ReceiptData {
  state: RepoState
  harnesses: HarnessName[]
  results: WriteResult[]
  configWritten: boolean
  gate?: GateResult
  settings?: SettingsMergeResult
  opsx: OpsxFile[]
  opsxRemoved: boolean
  notGitTree: boolean
  autoNote?: string
}

function printReceipt(target: string, d: ReceiptData): void {
  const lines: string[] = []
  const created = d.results.filter((r) => r.outcome === 'created').length
  const preserved = d.results.filter(
    (r) => r.outcome === 'preserved-modified' || r.outcome === 'preserved-foreign',
  )

  lines.push(`cospec initialized in ${target}  (state ${d.state})`)
  if (d.notGitTree) lines.push('  note: not a git work tree — hooks and drift gating assume git.')
  if (d.autoNote !== undefined) lines.push(`  ${d.autoNote}`)
  lines.push('')

  lines.push(`Schemas: 11 types in openspec/schemas/`)
  if (d.configWritten) lines.push('Config:  openspec/config.yaml (schema: feat)')
  if (created > 0) lines.push(`Files:   ${created} created`)
  if (preserved.length > 0) {
    lines.push(`Preserved: ${preserved.length} edited file(s) — new versions in .cospec-new`)
  }

  if (d.harnesses.length > 0) {
    lines.push(`Harness: ${d.harnesses.join(', ')}`)
  } else {
    lines.push('Harness: none (schemas only)')
  }

  if (d.settings !== undefined) {
    if (d.settings.status === 'unparseable') {
      lines.push('')
      lines.push('.claude/settings.json is not valid JSON — add this permission yourself:')
      lines.push(indent(d.settings.snippet))
    } else if (d.settings.added.length > 0) {
      lines.push(`Permissions: merged ${COSPEC_PERMISSION} into .claude/settings.json`)
    }
  }

  if (d.gate !== undefined) {
    if (d.gate.written.length > 0) lines.push(`Gate:    wrote ${d.gate.written.join(', ')}`)
    // hk.pkl / commitlint are whole-file configs: absent → written above,
    // present → paste-ready snippet (there is no additive-merge story for them).
    for (const snippet of d.gate.snippets) {
      lines.push('')
      lines.push(`Gate: ${snippet.file} already exists — paste-ready snippet:`)
      lines.push(indent(snippet.content))
    }
    // mise.toml is additively merged; report the outcome.
    const mise = d.gate.mise
    if (mise !== undefined) {
      if (mise.status === 'merged') {
        lines.push(
          `Gate:    merged ${mise.added.length} addition(s) into mise.toml (${mise.added.join(', ')})`,
        )
      } else if (mise.status === 'conflict') {
        lines.push('')
        lines.push(
          `Gate: mise.toml — merged ${mise.added.length} addition(s); ${mise.conflicts.length} key(s) differ from the gate and were left as-is:`,
        )
        for (const c of mise.conflicts) {
          lines.push(`  ${c.path}: yours=${c.existing} gate=${c.template}`)
        }
        lines.push(indent(mise.snippet))
      } else if (mise.status === 'unparseable') {
        lines.push('')
        lines.push('Gate: mise.toml is not valid TOML — add this yourself:')
        lines.push(indent(mise.snippet))
      }
      // 'unchanged' / 'created' (already in `written`) print nothing extra.
    }
  }

  if (d.opsx.length > 0) {
    lines.push('')
    if (d.opsxRemoved) {
      lines.push(`Removed ${d.opsx.length} leftover openspec (opsx) file(s).`)
    } else {
      lines.push(
        `Found ${d.opsx.length} leftover openspec (opsx) file(s) — two propose commands confuse agents:`,
      )
      for (const o of d.opsx) lines.push(`  ${o.relpath}`)
      lines.push(
        'Re-run with --remove-opsx to delete them (only provably openspec-generated files).',
      )
    }
  }

  if (d.harnesses.length > 0) {
    lines.push('')
    for (const h of d.harnesses) lines.push(RESTART_LINES[h])
  }

  lines.push('')
  lines.push('Try: /cospec:propose "feat: <what you want to build>"')
  lines.push('Lightweight change? /cospec:propose "ci: fix release workflow" — 3 short artifacts.')

  process.stdout.write(`${lines.join('\n')}\n`)
}

function indent(text: string): string {
  return text
    .replace(/\n$/, '')
    .split('\n')
    .map((l) => (l === '' ? '' : `    ${l}`))
    .join('\n')
}
