[install]
linker = "isolated"

[install.lockfile]
save = true

[run]
shell = "bun"
silent = false

[test]
coverage = false
coverageThreshold = { line = 0.95, function = 0.95, branch = 0.80, statement = 0.95 }
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"

telemetry = false
