// `generate()` and `update` for the GitHub Copilot cloud files (design decisions 7, 8 and 10):
// the files are emitted while opted in and re-synced on every run, removed on opt-out or when
// the tool is no longer configured (managed ones only; an edited one stays and is reported),
// and a failure the binary would catch becomes one Warning line while any other error
// propagates. `GenerateOptions.cloud` is the directive `init` resolved; absent, `generate()`
// resolves it from the config and the files, as `update` and `doctor` need.

import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { run as doctorRun } from '../../../src/commands/doctor.ts'
import { generate, run as updateRun } from '../../../src/commands/update.ts'
import { readManifest } from '../../../src/core/managed-files.ts'
import {
  COPILOT_AGENT_ALTERNATE_FILE,
  COPILOT_CLOUD_FILES,
} from '../../../src/harness/copilot-cloud.ts'
import { capture, captureAsync, cleanup, ctx, makeRepo } from './helpers.ts'

const WORKFLOW = COPILOT_CLOUD_FILES.setupSteps
const AGENT = COPILOT_CLOUD_FILES.agent
const COPILOT = ['github-copilot'] as const
const CONFLICT =
  'Conflicting Copilot agent profiles: preserve either .github/agents/cospec.md or .github/agents/cospec.agent.md'

let dir: string
beforeEach(() => {
  dir = makeRepo()
})
afterEach(() => cleanup(dir))

const put = (rel: string, text: string): void => {
  mkdirSync(join(dir, rel, '..'), { recursive: true })
  writeFileSync(join(dir, rel), text)
}
const read = (rel: string): string => readFileSync(join(dir, rel), 'utf8')
const has = (rel: string): boolean => existsSync(join(dir, rel))
const setCloud = (value: boolean | string): void =>
  put('openspec/config.yaml', `githubCopilot:\n  cloudAgent: ${value}\n`)
const outcomes = (results: { path: string; outcome: string }[]): Record<string, string> =>
  Object.fromEntries(
    results
      .filter((r) => ([WORKFLOW, AGENT] as string[]).includes(r.path))
      .map((r) => [r.path, r.outcome]),
  )
/** A repo with `github-copilot` configured (its skills on disk) and no cloud file. */
const configured = (): void => {
  generate(dir, { harnesses: [...COPILOT], cloud: 'leave' })
}
const update = (...args: string[]) =>
  captureAsync(() =>
    updateRun(
      ctx(
        dir,
        args.filter((a) => a !== '--json'),
        args.includes('--json'),
        'update',
      ),
    ),
  )

describe('generate() with an explicit directive', () => {
  test('write emits both files, and a second call reports them unchanged', () => {
    const first = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(outcomes(first.results)).toEqual({ [WORKFLOW]: 'created', [AGENT]: 'created' })
    expect(first.cloud).toEqual({
      present: [WORKFLOW, AGENT],
      collisions: [],
      removed: [],
      leftInPlace: [],
    })
    expect(read(WORKFLOW)).toContain('Generated by cospec')
    expect(readManifest(dir)?.files[WORKFLOW]).toBeDefined()
    const second = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(outcomes(second.results)).toEqual({ [WORKFLOW]: 'unchanged', [AGENT]: 'unchanged' })
    expect(second.cloud?.present).toEqual([WORKFLOW, AGENT])
  })

  test('remove takes away an unedited workflow and agent file', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    const off = generate(dir, { harnesses: [...COPILOT], cloud: 'remove' })
    expect(outcomes(off.results)).toEqual({ [WORKFLOW]: 'removed', [AGENT]: 'removed' })
    expect(off.cloud).toEqual({
      present: [],
      collisions: [],
      removed: [WORKFLOW, AGENT],
      leftInPlace: [],
    })
    expect(has(WORKFLOW) || has(AGENT)).toBe(false)
    expect(readManifest(dir)?.files[WORKFLOW]).toBeUndefined()
  })

  test('remove reports an edited file in leftInPlace, not as drift, and keeps its record', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    put(AGENT, `${read(AGENT)}\nMy rule.\n`)
    put(WORKFLOW, `${read(WORKFLOW)}# mine\n`)
    const off = generate(dir, { harnesses: [...COPILOT], cloud: 'remove' })
    expect(outcomes(off.results)).toEqual({})
    expect(off.cloud).toEqual({
      present: [],
      collisions: [],
      removed: [],
      leftInPlace: [WORKFLOW, AGENT],
    })
    expect(read(AGENT)).toContain('My rule.')
    expect(read(WORKFLOW)).toContain('# mine')
    expect(readManifest(dir)?.files[WORKFLOW]).toBeDefined()
  })

  test('remove never touches a file cospec did not write (OpenSpec own files, a foreign workflow)', () => {
    put('.github/agents/openspec.agent.md', 'theirs\n')
    put(WORKFLOW, 'name: mine\n')
    put(AGENT, 'also mine\n')
    const off = generate(dir, { harnesses: [...COPILOT], cloud: 'remove' })
    expect(off.cloud).toEqual({ present: [], collisions: [], removed: [], leftInPlace: [] })
    expect(read('.github/agents/openspec.agent.md')).toBe('theirs\n')
    expect(read(WORKFLOW)).toBe('name: mine\n')
    expect(read(AGENT)).toBe('also mine\n')
  })

  test('leave touches neither file and keeps the workflow record', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    put(WORKFLOW, `${read(WORKFLOW)}# mine\n`)
    const kept = readManifest(dir)?.files[WORKFLOW]
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'leave' })
    expect(outcomes(out.results)).toEqual({})
    expect(read(WORKFLOW)).toContain('# mine')
    expect(readManifest(dir)?.files[WORKFLOW]).toBe(kept)
  })

  test('a foreign workflow gets a sidecar and is a collision, and is never recorded as ours', () => {
    put(WORKFLOW, 'name: mine\n')
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(outcomes(out.results)[WORKFLOW]).toBe('preserved-foreign')
    expect(out.cloud?.collisions).toEqual([WORKFLOW])
    expect(out.cloud?.present).toEqual([AGENT])
    expect(read(WORKFLOW)).toBe('name: mine\n')
    expect(has(`${WORKFLOW}.cospec-new`)).toBe(true)
    expect(readManifest(dir)?.files[WORKFLOW]).toBeUndefined()
    // A later opt-out leaves it silently: it was never edited, because it was never ours.
    const off = generate(dir, { harnesses: [...COPILOT], cloud: 'remove' })
    expect(off.cloud?.leftInPlace).toEqual([])
    expect(read(WORKFLOW)).toBe('name: mine\n')
  })

  test('an edited agent file on write is a collision with a sidecar, not an overwrite', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    put(AGENT, `${read(AGENT)}\nMy rule.\n`)
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(outcomes(out.results)[AGENT]).toBe('preserved-modified')
    expect(out.cloud?.collisions).toEqual([AGENT])
    expect(read(AGENT)).toContain('My rule.')
    expect(has(`${AGENT}.cospec-new`)).toBe(true)
  })

  test('a dry run reports what it would do and writes nothing', () => {
    const would = generate(dir, { harnesses: [...COPILOT], cloud: 'write', dryRun: true })
    expect(outcomes(would.results)).toEqual({ [WORKFLOW]: 'created', [AGENT]: 'created' })
    expect(has('.github/workflows') || has('.github/agents')).toBe(false)
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    const wouldOff = generate(dir, { harnesses: [...COPILOT], cloud: 'remove', dryRun: true })
    expect(wouldOff.cloud?.removed).toEqual([WORKFLOW, AGENT])
    expect(has(WORKFLOW) && has(AGENT)).toBe(true)
  })

  test('the version override stamps the agent file', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write', version: '9.9.9' })
    expect(read(AGENT)).toContain('generatedBy: 9.9.9')
  })
})

describe('generate() resolving the directive itself', () => {
  test('a persisted true writes both files', () => {
    configured()
    setCloud(true)
    const out = generate(dir, { harnesses: [...COPILOT] })
    expect(out.cloud?.present).toEqual([WORKFLOW, AGENT])
  })

  test('a persisted false removes the managed files', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(false)
    const out = generate(dir, { harnesses: [...COPILOT] })
    expect(out.cloud?.removed).toEqual([WORKFLOW, AGENT])
  })

  test('false beats a managed file on disk, true beats a missing one', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(false)
    generate(dir, { harnesses: [...COPILOT] })
    expect(has(WORKFLOW) || has(AGENT)).toBe(false)
    setCloud(true)
    generate(dir, { harnesses: [...COPILOT] })
    expect(has(WORKFLOW) && has(AGENT)).toBe(true)
  })

  test('with no config, a managed file on disk keeps both files current (tier 3)', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    rmSync(join(dir, WORKFLOW))
    const out = generate(dir, { harnesses: [...COPILOT] })
    expect(outcomes(out.results)).toEqual({ [WORKFLOW]: 'created', [AGENT]: 'unchanged' })
  })

  test('with no config and no managed file the run is undecided and writes nothing', () => {
    configured()
    const out = generate(dir, { harnesses: [...COPILOT] })
    expect(outcomes(out.results)).toEqual({})
    expect(has('.github/workflows') || has('.github/agents')).toBe(false)
  })

  test('a malformed value is undecided and warns on stderr', () => {
    configured()
    setCloud('"yes"')
    const { err, out } = (() => {
      let result: ReturnType<typeof generate> | undefined
      const captured = capture(() => {
        result = generate(dir, { harnesses: [...COPILOT] })
        return 0
      })
      return { err: captured.err, out: result }
    })()
    expect(outcomes(out?.results ?? [])).toEqual({})
    expect(err).toContain("Invalid 'githubCopilot.cloudAgent' field in config (must be a boolean)")
  })

  test('github-copilot not among the harnesses removes the managed files, whatever the config', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    const out = generate(dir, { harnesses: ['claude'] })
    expect(out.cloud?.removed).toEqual([WORKFLOW, AGENT])
    expect(has(WORKFLOW) || has(AGENT)).toBe(false)
  })

  test('a config that cannot be read is not swallowed', () => {
    configured()
    mkdirSync(join(dir, 'openspec/config.yaml'), { recursive: true })
    expect(() => generate(dir, { harnesses: [...COPILOT] })).toThrow()
  })
})

describe('the alternate profile and the failures', () => {
  test('cospec.md present with no profile suppresses the agent file only', () => {
    put(COPILOT_AGENT_ALTERNATE_FILE, 'mine\n')
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(outcomes(out.results)).toEqual({ [WORKFLOW]: 'created' })
    expect(out.cloud?.present).toEqual([WORKFLOW])
    expect(has(AGENT)).toBe(false)
  })

  test('cospec.md present with an untouched managed profile removes the profile', () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    put(COPILOT_AGENT_ALTERNATE_FILE, 'mine\n')
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(outcomes(out.results)).toEqual({ [WORKFLOW]: 'unchanged', [AGENT]: 'removed' })
    expect(out.cloud?.removed).toEqual([AGENT])
    expect(has(AGENT)).toBe(false)
  })

  test('both profiles with the agent file unmanaged is recorded against the agent path', () => {
    put(COPILOT_AGENT_ALTERNATE_FILE, 'mine\n')
    put(AGENT, 'also mine\n')
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(out.failed).toEqual([{ path: AGENT, error: CONFLICT }])
    expect(has(WORKFLOW)).toBe(false)
    expect(read(AGENT)).toBe('also mine\n')
    expect(has('.github/skills')).toBe(true)
  })

  test('a managed path that is a directory is a recorded failure and nothing cloud is written', () => {
    mkdirSync(join(dir, AGENT), { recursive: true })
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(out.failed.map((f) => f.path)).toContain(AGENT)
    expect(out.failed.find((f) => f.path === AGENT)?.error).toContain(
      'Managed Copilot path is not a regular file',
    )
    expect(has(WORKFLOW)).toBe(false)
  })

  test('a parent that is a file is a recorded failure against the workflow', () => {
    put('.github/workflows', 'a file, not a directory')
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    expect(out.failed.find((f) => f.path === WORKFLOW)?.error).toContain(
      'Parent path is not a directory',
    )
  })

  test('removal guards a managed path that is a directory the same way', () => {
    mkdirSync(join(dir, WORKFLOW), { recursive: true })
    const out = generate(dir, { harnesses: [...COPILOT], cloud: 'remove' })
    expect(out.failed.find((f) => f.path === WORKFLOW)?.error).toContain(
      'Managed Copilot path is not a regular file',
    )
  })
})

describe('update', () => {
  test('re-syncs a deleted managed file while opted in, then reports up to date', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    rmSync(join(dir, WORKFLOW))
    const first = await update()
    expect(first.code).toBe(0)
    expect(first.out).toContain(WORKFLOW)
    expect(has(WORKFLOW)).toBe(true)
    expect((await update()).out).toContain('everything up to date')
  })

  test('opted in, out, in again: out removes the managed files and says so', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    setCloud(false)
    const off = await update()
    expect(off.code).toBe(0)
    expect(off.out).toContain('Removed: 2 Copilot cloud agent file(s) (opted out of cloud files)')
    expect(has(WORKFLOW) || has(AGENT)).toBe(false)
    setCloud(true)
    await update()
    expect(has(WORKFLOW) && has(AGENT)).toBe(true)
  })

  test('a hand-edited agent file survives opt-out, the managed workflow is removed', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    put(AGENT, `${read(AGENT)}\nMy rule.\n`)
    setCloud(false)
    const off = await update()
    expect(off.code).toBe(0)
    expect(off.out).toContain('Removed: 1 Copilot cloud agent file(s) (opted out of cloud files)')
    expect(off.out).toContain(
      `Left ${AGENT} in place: edited since cospec wrote it (opted out of cloud files).`,
    )
    expect(has(WORKFLOW)).toBe(false)
    expect(read(AGENT)).toContain('My rule.')
  })

  test('github-copilot not configured removes the managed files with its own reason', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    rmSync(join(dir, '.github/skills'), { recursive: true })
    rmSync(join(dir, '.github/prompts'), { recursive: true })
    const out = await update()
    expect(out.code).toBe(0)
    expect(out.out).toContain(
      'Removed: 2 Copilot cloud agent file(s) (github-copilot not configured)',
    )
    expect(has(WORKFLOW) || has(AGENT)).toBe(false)
  })

  test('undecided is silent on a run that is not interactive', async () => {
    configured()
    const out = await update()
    expect(out.out).not.toContain('opt-in')
    expect(out.out).not.toContain('Removed')
    expect(has(WORKFLOW)).toBe(false)
  })

  test('--check exits 1 for a missing managed cloud file and writes nothing', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    rmSync(join(dir, WORKFLOW))
    const out = await update('--check')
    expect(out.code).toBe(1)
    expect(out.out).toContain(WORKFLOW)
    expect(has(WORKFLOW)).toBe(false)
  })

  test('--check exits 1 when an opt-out would remove a managed file, and removes nothing', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(false)
    const out = await update('--check')
    expect(out.code).toBe(1)
    expect(has(WORKFLOW) && has(AGENT)).toBe(true)
  })

  test('--check is clean while opted in and in sync, and for an opted-out edited file', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    expect((await update('--check')).code).toBe(0)
    put(AGENT, `${read(AGENT)}\nMy rule.\n`)
    setCloud(false)
    rmSync(join(dir, WORKFLOW))
    expect((await update('--check')).code).toBe(0)
  })

  test('the conflict is one Warning line on stderr and the exit code is kept', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    put(COPILOT_AGENT_ALTERNATE_FILE, 'mine\n')
    put(AGENT, 'also mine\n')
    const out = await update()
    expect(out.code).toBe(0)
    expect(out.err).toBe(`Warning: failed to sync Copilot cloud agent files: ${CONFLICT}\n`)
    expect(out.out).not.toContain('Failed:')
  })

  test('a path guard keeps the exit code too', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    rmSync(join(dir, AGENT))
    mkdirSync(join(dir, AGENT), { recursive: true })
    const out = await update()
    expect(out.code).toBe(0)
    expect(out.err).toContain('Warning: failed to sync Copilot cloud agent files: ')
    expect(out.err).toContain('Managed Copilot path is not a regular file')
  })

  test('--json stays one document: removed files are listed, the warning goes to stderr', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(false)
    const out = await update('--json')
    const doc = JSON.parse(out.out) as { files: { path: string; outcome: string }[] }
    expect(outcomes(doc.files)).toEqual({ [WORKFLOW]: 'removed', [AGENT]: 'removed' })
    expect(out.err).toBe('')
  })

  test('a config that cannot be read propagates', async () => {
    configured()
    mkdirSync(join(dir, 'openspec/config.yaml'), { recursive: true })
    await expect(update()).rejects.toThrow()
  })
})

describe('doctor', () => {
  test('reports a missing managed cloud file as a missing managed file', async () => {
    generate(dir, { harnesses: [...COPILOT], cloud: 'write' })
    setCloud(true)
    rmSync(join(dir, WORKFLOW))
    const out = await captureAsync(() => doctorRun(ctx(dir, [], false, 'doctor')))
    expect(out.out).toContain(`managed file is missing: ${WORKFLOW}`)
  })
})
