import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { mkdirSync, mkdtempSync, readdirSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'

import { parse } from 'yaml'

import { canonFile } from '../../../src/canon/embedded.ts'
import {
  computeContentHash,
  MANAGED_AUTHOR,
  splitFrontmatter,
  writeManifest,
} from '../../../src/core/managed-files.ts'
import {
  assertCopilotCloudPaths,
  classifyCloudFile,
  classifyCloudFiles,
  classifyCopilotAgentReconciliation,
  COPILOT_AGENT_ALTERNATE_FILE,
  COPILOT_CLOUD_FILES,
  COPILOT_CLOUD_MARKER,
  copilotAgentContent,
  copilotAgentFrontmatter,
  copilotSetupStepsContent,
} from '../../../src/harness/copilot-cloud.ts'

let cwd: string

beforeEach(() => {
  cwd = mkdtempSync(join(tmpdir(), 'cospec-copilot-cloud-'))
})
afterEach(() => {
  rmSync(cwd, { recursive: true, force: true })
})

function put(rel: string, content: string): void {
  const full = join(cwd, rel)
  mkdirSync(dirname(full), { recursive: true })
  writeFileSync(full, content)
}

function track(rel: string, content: string): void {
  writeManifest(cwd, { cospecVersion: '0.0.0', files: { [rel]: computeContentHash(content) } })
}

/** A line that runs bare `openspec` as a command (a path such as `openspec/changes/` is fine). */
const BARE_OPENSPEC = /(^|[\s`|(])openspec(\s|$)/i

describe('the workflow template', () => {
  const text = copilotSetupStepsContent()

  test('keeps the job name GitHub requires and installs and verifies cospec', () => {
    const doc = parse(text) as { jobs: Record<string, { steps: { run?: string }[] }> }
    expect(Object.keys(doc.jobs)).toEqual(['copilot-setup-steps'])
    const runs = doc.jobs['copilot-setup-steps']!.steps.map((s) => s.run).filter(Boolean)
    expect(runs).toEqual(['npm install -g @aligned-team/cospec', 'cospec --version'])
  })

  test('carries the marker as its first line and never names the other tool', () => {
    expect(COPILOT_CLOUD_MARKER).toBe(
      'Generated by cospec for GitHub Copilot coding agent support.',
    )
    expect(text.split('\n')[0]).toBe(`# ${COPILOT_CLOUD_MARKER}`)
    expect(text).not.toMatch(/fission/i)
    expect(text.split('\n').filter((l) => BARE_OPENSPEC.test(l))).toEqual([])
  })
})

describe('the agent template', () => {
  const { fields, body } = copilotAgentFrontmatter()

  test('is named cospec with upstream tools', () => {
    expect(fields.name).toBe('cospec')
    expect(typeof fields.description).toBe('string')
    expect(fields.tools).toEqual(['execute', 'read', 'search', 'edit'])
  })

  test('renders with cospec provenance in metadata and a body hash that matches', () => {
    const rendered = copilotAgentContent()
    const split = splitFrontmatter(rendered)
    const meta = split.frontmatter!.metadata as Record<string, unknown>
    expect(meta.author).toBe(MANAGED_AUTHOR)
    expect(meta.generatedBy).toMatch(/^cospec@/)
    expect(meta.contentHash).toBe(computeContentHash(split.body))
    // GitHub documents `metadata` as a string name-value map.
    expect(Object.values(meta).every((v) => typeof v === 'string')).toBe(true)
    expect(split.body).toBe(body)
  })

  test('carries the marker, walks the cospec gate, and runs no bare openspec', () => {
    expect(body).toContain(`<!-- ${COPILOT_CLOUD_MARKER} -->`)
    for (const command of ['new', 'instructions', 'validate', 'apply', 'archive']) {
      expect(body).toContain(`cospec ${command}`)
    }
    for (const code of ['`0`', '`2`', '`3`']) expect(body).toContain(code)
    expect(body).not.toMatch(/fission/i)
    expect(body.split('\n').filter((l) => BARE_OPENSPEC.test(l))).toEqual([])
  })
})

describe('the embedded registry', () => {
  test('registers every template in canon/github-copilot', () => {
    const dir = dirname(canonFile('github-copilot/cospec.agent.md.tpl'))
    const onDisk = readdirSync(dir)
      .filter((f) => f.endsWith('.tpl'))
      .toSorted()
    expect(onDisk).toEqual(['copilot-setup-steps.yml.tpl', 'cospec.agent.md.tpl'])
    for (const name of onDisk) expect(() => canonFile(`github-copilot/${name}`)).not.toThrow()
  })

  test('throws on an unregistered canon path', () => {
    expect(() => canonFile('github-copilot/missing.tpl')).toThrow(/not registered/)
  })
})

describe('the managed classification', () => {
  test('the two paths are cospec.agent.md and copilot-setup-steps.yml', () => {
    expect(COPILOT_CLOUD_FILES).toEqual({
      setupSteps: '.github/workflows/copilot-setup-steps.yml',
      agent: '.github/agents/cospec.agent.md',
    })
  })

  test('an absent file is absent', () => {
    expect(classifyCloudFiles(cwd)).toEqual({
      [COPILOT_CLOUD_FILES.setupSteps]: 'absent',
      [COPILOT_CLOUD_FILES.agent]: 'absent',
    })
  })

  test('an untouched agent file is managed', () => {
    put(COPILOT_CLOUD_FILES.agent, copilotAgentContent())
    expect(classifyCloudFile(cwd, COPILOT_CLOUD_FILES.agent)).toBe('managed')
  })

  test('an edited agent file is modified', () => {
    put(COPILOT_CLOUD_FILES.agent, `${copilotAgentContent()}\nOur own rule.\n`)
    expect(classifyCloudFile(cwd, COPILOT_CLOUD_FILES.agent)).toBe('modified')
  })

  test('an agent file with no cospec provenance is foreign', () => {
    put(COPILOT_CLOUD_FILES.agent, '---\nname: mine\n---\nhello\n')
    expect(classifyCloudFile(cwd, COPILOT_CLOUD_FILES.agent)).toBe('foreign')
  })

  test('an untouched, tracked workflow is managed', () => {
    const content = copilotSetupStepsContent()
    put(COPILOT_CLOUD_FILES.setupSteps, content)
    track(COPILOT_CLOUD_FILES.setupSteps, content)
    expect(classifyCloudFile(cwd, COPILOT_CLOUD_FILES.setupSteps)).toBe('managed')
  })

  test('an edited, tracked workflow is modified', () => {
    const content = copilotSetupStepsContent()
    put(COPILOT_CLOUD_FILES.setupSteps, `${content}# ours\n`)
    track(COPILOT_CLOUD_FILES.setupSteps, content)
    expect(classifyCloudFile(cwd, COPILOT_CLOUD_FILES.setupSteps)).toBe('modified')
  })

  test('a workflow the manifest does not track is foreign, marker or not', () => {
    put(COPILOT_CLOUD_FILES.setupSteps, copilotSetupStepsContent())
    expect(classifyCloudFile(cwd, COPILOT_CLOUD_FILES.setupSteps)).toBe('foreign')
  })

  test("OpenSpec's own copilot-setup-steps.yml is foreign", () => {
    const upstream =
      '# Generated by OpenSpec for GitHub Copilot coding agent support.\n\nname: "Copilot Setup Steps"\n'
    put(COPILOT_CLOUD_FILES.setupSteps, upstream)
    track('.github/workflows/other.yml', 'unrelated')
    expect(classifyCloudFile(cwd, COPILOT_CLOUD_FILES.setupSteps)).toBe('foreign')
  })

  test("OpenSpec's own openspec.agent.md is never ours, even with cospec metadata", () => {
    put('.github/agents/openspec.agent.md', copilotAgentContent())
    expect(classifyCloudFile(cwd, '.github/agents/openspec.agent.md')).toBe('foreign')
    expect(classifyCloudFile(cwd, '.github/agents/other.agent.md')).toBe('absent')
    expect(Object.values(COPILOT_CLOUD_FILES)).not.toContain('.github/agents/openspec.agent.md')
  })
})

describe('the alternate-profile classifier', () => {
  const CONFLICT = `Conflicting Copilot agent profiles: preserve either ${COPILOT_AGENT_ALTERNATE_FILE} or ${COPILOT_CLOUD_FILES.agent}`

  test('the alternate is cospec.md', () => {
    expect(COPILOT_AGENT_ALTERNATE_FILE).toBe('.github/agents/cospec.md')
  })

  test('no alternate means reconcile', () => {
    expect(classifyCopilotAgentReconciliation(cwd)).toBe('reconcile')
    put(COPILOT_CLOUD_FILES.agent, 'user content')
    expect(classifyCopilotAgentReconciliation(cwd)).toBe('reconcile')
  })

  test('an alternate with no profile means skip', () => {
    put(COPILOT_AGENT_ALTERNATE_FILE, 'mine')
    expect(classifyCopilotAgentReconciliation(cwd)).toBe('skip')
  })

  test('an alternate with an untouched managed profile means remove it', () => {
    put(COPILOT_AGENT_ALTERNATE_FILE, 'mine')
    put(COPILOT_CLOUD_FILES.agent, copilotAgentContent())
    expect(classifyCopilotAgentReconciliation(cwd)).toBe('remove-managed')
  })

  test('an alternate with an edited or foreign profile throws the conflict sentence', () => {
    put(COPILOT_AGENT_ALTERNATE_FILE, 'mine')
    put(COPILOT_CLOUD_FILES.agent, `${copilotAgentContent()}edit\n`)
    expect(() => classifyCopilotAgentReconciliation(cwd)).toThrow(CONFLICT)
    put(COPILOT_CLOUD_FILES.agent, 'foreign')
    expect(() => classifyCopilotAgentReconciliation(cwd)).toThrow(CONFLICT)
  })
})

describe('the path guards', () => {
  test('a clean project passes', () => {
    expect(() => assertCopilotCloudPaths(cwd)).not.toThrow()
  })

  test('a parent that is a file is refused', () => {
    put('.github/workflows', 'a file, not a directory')
    expect(() => assertCopilotCloudPaths(cwd)).toThrow(/Parent path is not a directory/)
  })

  test('an ancestor that is a file surfaces the errno, not a swallowed success', () => {
    put('.github', 'a file, not a directory')
    expect(() => assertCopilotCloudPaths(cwd)).toThrow(/ENOTDIR/)
  })

  test('a managed path that is a directory is refused', () => {
    mkdirSync(join(cwd, COPILOT_CLOUD_FILES.agent), { recursive: true })
    expect(() => assertCopilotCloudPaths(cwd)).toThrow(/Managed Copilot path is not a regular file/)
  })

  test('a symlink to a regular file is accepted', () => {
    put('target.md', 'x')
    mkdirSync(join(cwd, '.github', 'agents'), { recursive: true })
    symlinkSync(join(cwd, 'target.md'), join(cwd, COPILOT_AGENT_ALTERNATE_FILE))
    expect(() => assertCopilotCloudPaths(cwd)).not.toThrow()
  })
})
