// `renderPowerShellCompletion` unit tests (ledger rows 8.1, 8.2). The script is
// rendered from the same `CompletionSpec` as bash, zsh and fish, so these
// tests read the generated data block back and compare it with the table: the
// flags a command's block offers are the table's offered flags and no pending
// one, the tooltips are the table's descriptions, and every string is a
// single-quoted PowerShell literal.

import { afterAll, beforeAll, describe, expect, test } from 'bun:test'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  COMMAND_TABLE,
  GLOBAL_FLAGS,
  isPending,
  offeredFlags,
} from '../../../src/core/command-table.ts'
import { renderPowerShellCompletion } from '../../../src/core/completions/powershell.ts'
import { buildCompletionSpec, offeredFlagTokens } from '../../../src/core/completions/spec.ts'
import {
  commandBlock,
  commandFlags,
  commandNames,
  quoted,
  stringArray,
  subcommandBlock,
  subcommandFlags,
  subcommandNames,
} from './powershell-script.ts'

const spec = buildCompletionSpec()
const script = renderPowerShellCompletion(spec)
const visibleRows = COMMAND_TABLE.filter((row) => !row.hidden)

describe('renderPowerShellCompletion: registration', () => {
  test('registers a native completer for cospec', () => {
    expect(script).toContain('Register-ArgumentCompleter -Native -CommandName cospec')
  })

  test('the header names cospec and no other tool', () => {
    expect(script.split('\n')[0]).toBe(
      "# PowerShell completion for cospec, generated by 'cospec completion powershell'.",
    )
  })
})

describe('renderPowerShellCompletion: commands', () => {
  test('lists every non-hidden command once, in table order, and no hidden one', () => {
    expect(commandNames(script)).toEqual(visibleRows.map((row) => row.name))
    for (const hidden of COMMAND_TABLE.filter((row) => row.hidden))
      expect(commandNames(script)).not.toContain(hidden.name)
  })

  test('each command carries its summary as the tooltip', () => {
    for (const row of visibleRows)
      expect(commandBlock(script, row.name)).toContain(`Description = '${quoted(row.summary)}'`)
  })
})

describe('renderPowerShellCompletion: flags', () => {
  for (const row of visibleRows) {
    test(`${row.name}: offers the table's offered flags then the globals the row accepts, nothing pending`, () => {
      const block = commandBlock(script, row.name)!
      const command = spec.commands.find((c) => c.name === row.name)!
      expect(commandFlags(block).map((f) => f.name)).toEqual([
        ...new Set([...offeredFlagTokens(row.flags), ...command.globalFlags]),
      ])
      for (const flag of row.flags.filter((f) => isPending(f.status)))
        expect(commandFlags(block).map((f) => f.name)).not.toContain(flag.name)
      for (const flag of row.flags.filter((f) => f.hidden === true))
        expect(commandFlags(block).map((f) => f.name)).not.toContain(flag.name)
    })

    test(`${row.name}: each flag's tooltip is the table's description, short and long alike`, () => {
      const block = commandBlock(script, row.name)!
      const tooltips = new Map(commandFlags(block).map((f) => [f.name, f.description]))
      for (const flag of offeredFlags(row)) {
        expect(tooltips.get(flag.name)).toBe(quoted(flag.description))
        if (flag.short !== undefined)
          expect(tooltips.get(flag.short)).toBe(quoted(flag.description))
      }
    })

    test(`${row.name}: the flags that take a value are listed as such`, () => {
      const block = commandBlock(script, row.name)!
      const valued = offeredFlags(row)
        .filter((flag) => flag.takesValue === true)
        .flatMap((flag) => offeredFlagTokens([flag]))
      const accepted = spec.commands.find((c) => c.name === row.name)!.globalFlags
      const valuedGlobals = GLOBAL_FLAGS.filter(
        (flag) => flag.takesValue === true && accepted.includes(flag.name),
      ).map((flag) => flag.name)
      expect(stringArray(block, 'ValueFlags', 16).toSorted()).toEqual(
        [...valued, ...valuedGlobals].toSorted(),
      )
    })
  }

  test('a row that refuses --store is not offered it after its name', () => {
    expect(commandFlags(commandBlock(script, 'init')!).map((f) => f.name)).not.toContain('--store')
    expect(commandFlags(commandBlock(script, 'list')!).map((f) => f.name)).toContain('--store')
    expect(script).toMatch(/GlobalValueFlags = @\([^)]*'--store'/)
  })

  test('the program-level globals carry the table descriptions and -V/--version', () => {
    for (const flag of offeredFlags({ flags: GLOBAL_FLAGS }))
      expect(script).toContain(`Name = '${flag.name}'; Description = '${quoted(flag.description)}'`)
    expect(script).toContain("Name = '--version'; Description = 'Show version'")
    expect(script).toContain("Name = '-V'; Description = 'Show version'")
  })
})

describe('renderPowerShellCompletion: subcommands, values and dynamic sources', () => {
  for (const row of visibleRows.filter((r) => (r.subcommands ?? []).length > 0)) {
    test(`${row.name}: offers each non-pending subcommand with its flags, and no pending one`, () => {
      const block = commandBlock(script, row.name)!
      const offered = (row.subcommands ?? []).filter((sub) => !isPending(sub.status))
      expect(subcommandNames(block)).toEqual(offered.map((sub) => sub.name))
      for (const sub of offered) {
        const subBlock = subcommandBlock(block, sub.name)!
        expect(subBlock).toContain(`Description = '${quoted(sub.summary)}'`)
        const names = subcommandFlags(subBlock).map((f) => f.name)
        for (const token of offeredFlagTokens(sub.flags)) expect(names).toContain(token)
        for (const flag of sub.flags.filter((f) => isPending(f.status)))
          expect(names).not.toContain(flag.name)
      }
    })
  }

  test('the closed value set of a positional is read from the table', () => {
    const completion = commandBlock(script, 'completion')!
    const row = COMMAND_TABLE.find((r) => r.name === 'completion')!
    const first = row.positionals[0]!
    expect(stringArray(completion, 'Choices', 16)).toEqual([...(first.values ?? [])])
    expect(stringArray(commandBlock(script, 'new')!, 'Choices', 16)).toEqual([])
  })

  test('dynamic sources are the model: positional, flag value and subcommand positional', () => {
    expect(stringArray(commandBlock(script, 'show')!, 'Sources', 16)).toEqual(['changes', 'specs'])
    expect(commandBlock(script, 'status')!).toContain(
      "FlagSources = @{ '--change' = 'changes'; '--schema' = 'schemas' }",
    )
    const schema = commandBlock(script, 'schema')!
    expect(stringArray(subcommandBlock(schema, 'which')!, 'Sources', 24)).toEqual(['schemas'])
  })

  test('every dynamic source is resolved through cospec __complete, failure swallowed', () => {
    expect(script).toContain('cospec __complete $Source 2>$null')
    expect(script).toMatch(/try \{[^}]*cospec __complete \$Source[^}]*\} catch \{/)
  })
})

describe('renderPowerShellCompletion: text', () => {
  test('names no openspec binary: no code or comment line does', () => {
    // A tooltip is the table's own `--help` description (asserted above, byte
    // for byte), and three of those mention OpenSpec's tool or file by name
    // (`init --remove-opsx`, `validate --archived`, `new --goal`'s
    // `.openspec.yaml`). Those are prose about the wrapped tool, never an
    // invocation; the failure this guards is a script line that RUNS it, so
    // the tooltip literals are masked before the check.
    const outsideTooltips = script.replaceAll(/Description = '(?:[^']|'')*'/g, "Description = ''")
    expect(outsideTooltips).not.toMatch(/\bopenspec\b/i)
  })

  test('is ASCII only, LF terminated, with no control character', () => {
    expect(script).toMatch(/^[\x20-\x7e\n]*$/)
    expect(script.endsWith('\n')).toBe(true)
  })

  test('single-quotes every string: no double quote and no backtick outside a literal', () => {
    // A tooltip may hold a double quote (`--sort`'s help does); inside a
    // single-quoted literal it is inert, as the `$` and backtick are.
    const outsideLiterals = script
      .split('\n')
      .filter((line) => !line.trimStart().startsWith('#'))
      .join('\n')
      .replaceAll(/'(?:[^']|'')*'/g, "''")
    expect(outsideLiterals).not.toContain('"')
    expect(outsideLiterals).not.toContain('`')
  })

  test('a summary or description cannot expand: quote doubled, dollar and backtick literal', () => {
    const hostile = structuredClone(spec)
    hostile.commands[0]!.summary = "it's $(Remove-Item x) `n $env:HOME"
    const rendered = renderPowerShellCompletion(hostile)
    expect(rendered).toContain("Description = 'it''s $(Remove-Item x) `n $env:HOME'")
  })

  test('refuses text it cannot carry as ASCII instead of mangling it', () => {
    const odd = structuredClone(spec)
    odd.commands[0]!.summary = 'a — b'
    expect(() => renderPowerShellCompletion(odd)).toThrow(/non-ASCII/)
    const multiline = structuredClone(spec)
    multiline.commands[0]!.summary = 'a\nb'
    expect(() => renderPowerShellCompletion(multiline)).toThrow(/control character/)
  })
})

describe('renderPowerShellCompletion: shape no parser will check here', () => {
  // Nothing in CI runs `pwsh`, so the two parse errors upstream's generator
  // guards against are checked structurally: a trailing comma before `)` and
  // brackets that do not balance outside strings and comments.
  const code = script
    .split('\n')
    .filter((line) => !line.trimStart().startsWith('#'))
    .join('\n')
    .replaceAll(/'(?:[^']|'')*'/g, "''")

  test('no array ends in a trailing comma', () => {
    expect(code).not.toMatch(/,\s*\)/)
    expect(code).not.toMatch(/,\s*$/m)
  })

  test('braces, parentheses and brackets balance outside strings', () => {
    for (const [open, close] of [
      ['{', '}'],
      ['(', ')'],
      ['[', ']'],
    ] as const)
      expect(code.split(open).length).toBe(code.split(close).length)
  })

  test('renders the same script twice', () => {
    expect(renderPowerShellCompletion(buildCompletionSpec())).toBe(script)
  })
})

// `pwsh` is not assumed on PATH (nor in CI); where it is, the script is parsed
// and driven through PowerShell's own tab expansion.
const pwsh = Bun.which('pwsh')

describe.skipIf(pwsh === null)('renderPowerShellCompletion: under pwsh', () => {
  let dir = ''
  let file = ''
  beforeAll(() => {
    dir = mkdtempSync(join(tmpdir(), 'cospec-pwsh-'))
    file = join(dir, 'CospecCompletion.ps1')
    writeFileSync(file, script)
  })
  afterAll(() => rmSync(dir, { recursive: true, force: true }))

  function pwshRun(command: string): { code: number; out: string } {
    const result = Bun.spawnSync([pwsh!, '-NoProfile', '-NonInteractive', '-Command', command], {
      env: { ...process.env, COSPEC_PS_FILE: file },
    })
    return { code: result.exitCode, out: result.stdout.toString() + result.stderr.toString() }
  }

  test('parses with no error', () => {
    const { code, out } = pwshRun(
      '$errs = $null; [void][System.Management.Automation.Language.Parser]::ParseFile($env:COSPEC_PS_FILE, [ref]$null, [ref]$errs); if ($errs.Count) { $errs | ForEach-Object { $_.Message }; exit 1 }',
    )
    expect(out).toBe('')
    expect(code).toBe(0)
  })

  test('tab expansion completes commands, flags and subcommands', () => {
    const expand = (line: string): string[] => {
      const { out } = pwshRun(
        `. $env:COSPEC_PS_FILE; (TabExpansion2 '${line}' ${line.length}).CompletionMatches | ForEach-Object { $_.CompletionText }`,
      )
      return out.split('\n').filter((l) => l !== '')
    }
    expect(expand('cospec va')).toContain('validate')
    expect(expand('cospec validate --st')).toContain('--strict')
    expect(expand('cospec schema ')).toContain('which')
  })
})
