// bash completion generator. Emits a single `_cospec` function plus its
// `complete -F` registration — no rc-file mutation: writing the script and
// wiring the shell to load it is `cospec completion install`'s job
// (core/completions/install.ts). Dynamic ids come from `cospec __complete`,
// which fails silently, so a Tab in a non-repo directory offers nothing rather
// than printing an error mid-completion.

import { type CompletionSpec, narrowedGlobals } from './spec.ts'

/** Escape for a bash/zsh single-quoted string. */
export function escapeSingleQuoted(value: string): string {
  return value.replaceAll("'", String.raw`'\''`)
}

function caseArm(name: string, body: string[]): string {
  return [`    ${name})`, ...body.map((line) => `      ${line}`), '      ;;'].join('\n')
}

export function renderBashCompletion(spec: CompletionSpec): string {
  const names = spec.commands.map((c) => c.name).join(' ')
  const globals = spec.globalFlags.join(' ')

  const flagArms = spec.commands
    .filter((c) => c.flags.length > 0)
    .map((c) => caseArm(c.name, [`flags='${escapeSingleQuoted(c.flags.join(' '))}'`]))
    .join('\n')

  const globalArms = narrowedGlobals(spec)
    .map((c) => caseArm(c.name, [`globals='${escapeSingleQuoted(c.globalFlags.join(' '))}'`]))
    .join('\n')

  const positionalArms = spec.commands
    .filter((c) => c.positional.length > 0)
    .map((c) => caseArm(c.name, [`sources='${c.positional.join(' ')}'`]))
    .join('\n')

  const subcommandArms = spec.commands
    .flatMap((c) =>
      Object.entries(c.subcommandPositional).map(([sub, sources]) =>
        caseArm(`'${c.name} ${sub}'`, [`sources='${sources.join(' ')}'`]),
      ),
    )
    .join('\n')

  const flagValueArms = spec.commands
    .filter((c) => Object.keys(c.flagValues).length > 0)
    .map((c) =>
      caseArm(
        c.name,
        Object.entries(c.flagValues).map(
          (entry) => `[[ $prev == '${escapeSingleQuoted(entry[0])}' ]] && sources='${entry[1]}'`,
        ),
      ),
    )
    .join('\n')

  return `# bash completion for cospec — generated by 'cospec completion bash'.
# Install: eval "$(cospec completion bash)" in ~/.bashrc

_cospec_dynamic() {
  cospec __complete "$1" 2>/dev/null | cut -f1
}

_cospec() {
  local cur prev cmd sub i j subpos flags sources items
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev=""
  [[ $COMP_CWORD -gt 0 ]] && prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local globals='${escapeSingleQuoted(globals)}'
  local commands='${escapeSingleQuoted(names)}'

  cmd=""
  for (( i = 1; i < COMP_CWORD; i++ )); do
    case "\${COMP_WORDS[i]}" in
      -*) ;;
      *) cmd="\${COMP_WORDS[i]}"; break ;;
    esac
  done

  if [[ -z $cmd ]]; then
    COMPREPLY=( $(compgen -W "$commands $globals" -- "$cur") )
    return 0
  fi

  # The subcommand after the command, and how many positionals follow it.
  sub=""
  subpos=0
  for (( j = i + 1; j < COMP_CWORD; j++ )); do
    case "\${COMP_WORDS[j]}" in
      -*) ;;
      *) if [[ -z $sub ]]; then sub="\${COMP_WORDS[j]}"; else subpos=$((subpos + 1)); fi ;;
    esac
  done

  sources=""
  case "$cmd" in
${flagValueArms}
  esac

  if [[ -z $sources && $cur == -* ]]; then
    flags=""
    case "$cmd" in
${flagArms}
    esac
    case "$cmd" in
${globalArms}
    esac
    COMPREPLY=( $(compgen -W "$flags $globals" -- "$cur") )
    return 0
  fi

  if [[ -z $sources && -n $sub && $subpos -eq 0 ]]; then
    case "$cmd $sub" in
${subcommandArms}
    esac
  fi

  if [[ -z $sources ]]; then
    case "$cmd" in
${positionalArms}
    esac
  fi

  items=""
  for i in $sources; do
    items="$items $(_cospec_dynamic "$i")"
  done
  COMPREPLY=( $(compgen -W "$items" -- "$cur") )
  return 0
}

complete -F _cospec cospec
`
}
