// fish completion generator. One `complete -c cospec` line per command, flag,
// and dynamic slot — fish's model needs no dispatch function of its own.

import type { CompletionSpec } from './spec.ts'

/** Escape for a fish single-quoted string (only `\` and `'` are special). */
export function escapeFish(value: string): string {
  return value.replaceAll('\\', '\\\\').replaceAll("'", String.raw`\'`)
}

/** `--flag` → `-l flag`; `-x` → `-s x`. */
function flagArg(flag: string): string {
  return flag.startsWith('--') ? `-l ${flag.slice(2)}` : `-s ${flag.slice(1)}`
}

function dynamicArg(sources: string[]): string {
  return sources.map((source) => `(cospec __complete ${source} 2>/dev/null | cut -f1)`).join(' ')
}

export function renderFishCompletion(spec: CompletionSpec): string {
  const lines: string[] = [
    "# fish completion for cospec — generated by 'cospec completion fish'.",
    '# Install: cospec completion fish > ~/.config/fish/completions/cospec.fish',
    '',
    '# No file completion by default; commands opt into dynamic ids below.',
    'complete -c cospec -f',
    '',
  ]

  for (const flag of spec.globalFlags) lines.push(`complete -c cospec ${flagArg(flag)}`)
  lines.push('')

  for (const command of spec.commands) {
    lines.push(
      `complete -c cospec -n __fish_use_subcommand -a ${command.name} -d '${escapeFish(command.summary)}'`,
    )
  }
  lines.push('')

  for (const command of spec.commands) {
    const seen = `-n '__fish_seen_subcommand_from ${command.name}'`
    for (const flag of command.flags) {
      const source = command.flagValues[flag]
      const value = source === undefined ? '' : ` -x -a "${dynamicArg([source])}"`
      lines.push(`complete -c cospec ${seen} ${flagArg(flag)}${value}`)
    }
    if (command.positional.length > 0)
      lines.push(`complete -c cospec ${seen} -a "${dynamicArg(command.positional)}"`)
  }
  lines.push('')

  return lines.join('\n')
}
