// PowerShell completion generator. The script is a data block (`Get-CospecModel`)
// rendered from the same `CompletionSpec` as the other shells, read by a short
// fixed engine registered with `Register-ArgumentCompleter -Native`. Every
// string is a single-quoted PowerShell literal, where only `'` is special, so
// no `$`, backtick or `$(...)` in a summary or description can expand. The data
// block is newline-separated, never comma-separated: PowerShell rejects a
// trailing comma before `)`, and nothing in CI parses the script.
//
// The layout is part of the contract: a command is a `@{` at 12 spaces, its own
// flags sit at 20, a subcommand's `@{` at 20 and its flags at 28, which is how
// the unit tests (`test/unit/core/powershell-script.ts`) read it back.

import type { CompletionFlagInfo, CompletionSpec } from './spec.ts'

/**
 * A PowerShell single-quoted string. Text outside printable ASCII is refused
 * rather than transliterated: the script is written into a user's profile
 * directory in whatever encoding the profile has, and PowerShell reads curly
 * quotes as string delimiters.
 */
export function quotePowerShell(text: string): string {
  for (const char of text) {
    const code = char.codePointAt(0)!
    const hex = `U+${code.toString(16).toUpperCase().padStart(4, '0')}`
    if (code >= 0x80)
      throw new Error(`cospec completion powershell: non-ASCII character ${hex} in ${text}`)
    if (code < 0x20 || code === 0x7f)
      throw new Error(`cospec completion powershell: control character ${hex} in ${text}`)
  }
  return `'${text.replaceAll("'", "''")}'`
}

const array = (values: readonly string[]): string => `@(${values.map(quotePowerShell).join(', ')})`

/** A surface's flags: its own, then the globals its row accepts, each token once. */
function mergedFlags(
  flags: readonly string[],
  info: Record<string, CompletionFlagInfo>,
  globalFlags: readonly string[],
  globalInfo: Record<string, CompletionFlagInfo>,
): { tokens: string[]; info: Record<string, CompletionFlagInfo> } {
  return {
    tokens: [...new Set([...flags, ...globalFlags])],
    info: { ...globalInfo, ...info },
  }
}

function surface(
  indent: number,
  header: string[],
  merged: { tokens: string[]; info: Record<string, CompletionFlagInfo> },
  flagValues: Record<string, string>,
  choices: readonly string[],
  sources: readonly string[],
): string[] {
  const pad = ' '.repeat(indent)
  const entries = Object.entries(flagValues).map(
    ([flag, source]) => `${quotePowerShell(flag)} = ${quotePowerShell(source)}`,
  )
  return [
    ...header.map((line) => `${pad}${line}`),
    `${pad}Flags = @(`,
    ...merged.tokens.map(
      (token) =>
        `${pad}    @{ Name = ${quotePowerShell(token)}; Description = ${quotePowerShell(merged.info[token]!.description)} }`,
    ),
    `${pad})`,
    `${pad}ValueFlags = ${array(merged.tokens.filter((token) => merged.info[token]!.takesValue))}`,
    `${pad}FlagSources = @{${entries.length === 0 ? '' : ` ${entries.join('; ')} `}}`,
    `${pad}Choices = ${array(choices)}`,
    `${pad}Sources = ${array(sources)}`,
  ]
}

export function renderPowerShellCompletion(spec: CompletionSpec): string {
  const globals = spec.globalFlags.map(
    (flag) =>
      `            @{ Name = ${quotePowerShell(flag)}; Description = ${quotePowerShell(spec.globalFlagInfo[flag]!.description)} }`,
  )
  const globalValueFlags = spec.globalFlags.filter((flag) => spec.globalFlagInfo[flag]!.takesValue)

  const commands = spec.commands.flatMap((command) => {
    const merged = mergedFlags(
      command.flags,
      command.flagInfo,
      command.globalFlags,
      spec.globalFlagInfo,
    )
    const subcommands = command.subcommands.flatMap((sub) => [
      '                    @{',
      ...surface(
        24,
        [`Name = ${quotePowerShell(sub.name)}`, `Description = ${quotePowerShell(sub.summary)}`],
        mergedFlags(sub.flags, sub.flagInfo, command.globalFlags, spec.globalFlagInfo),
        {},
        sub.choices,
        command.subcommandPositional[sub.name] ?? [],
      ),
      '                    }',
    ])
    return [
      '            @{',
      ...surface(
        16,
        [
          `Name = ${quotePowerShell(command.name)}`,
          `Description = ${quotePowerShell(command.summary)}`,
        ],
        merged,
        command.flagValues,
        command.choices,
        command.positional,
      ),
      subcommands.length === 0
        ? '                Subcommands = @()'
        : ['                Subcommands = @(', ...subcommands, '                )'].join('\n'),
      '            }',
    ]
  })

  return `# PowerShell completion for cospec, generated by 'cospec completion powershell'.
# Install: cospec completion install powershell

# Ids come from 'cospec __complete'; a failure (no repo, no cospec) offers nothing.
function Get-CospecDynamic {
    param([string]$Source)
    try {
        $output = cospec __complete $Source 2>$null
    } catch {
        return
    }
    foreach ($line in @($output)) {
        $id = ($line -split '\\t')[0]
        if ($id) { $id }
    }
}

function ConvertTo-CospecItem {
    param([string[]]$Names)
    foreach ($name in $Names) {
        if ($name) { @{ Name = $name; Description = $name } }
    }
}

function Get-CospecCompletionResult {
    param([object[]]$Items, [string]$Word, [string]$Type)
    foreach ($item in $Items) {
        if ($item.Name.StartsWith($Word, [System.StringComparison]::OrdinalIgnoreCase)) {
            [System.Management.Automation.CompletionResult]::new($item.Name, $item.Name, $Type, $item.Description)
        }
    }
}

# The operands of a word list: not a flag, not a value-taking flag's value.
function Get-CospecOperand {
    param([string[]]$Words, [string[]]$ValueFlags)
    $skip = $false
    foreach ($word in $Words) {
        if ($skip) { $skip = $false; continue }
        if ($ValueFlags -contains $word) { $skip = $true; continue }
        if ($word.StartsWith('-')) { continue }
        $word
    }
}

function Get-CospecModel {
    @{
        GlobalValueFlags = ${array(globalValueFlags)}
        Globals = @(
${globals.join('\n')}
        )
        Commands = @(
${commands.join('\n')}
        )
    }
}

Register-ArgumentCompleter -Native -CommandName cospec -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $model = Get-CospecModel
    $words = @($commandAst.ToString() -split '\\s+' | Where-Object { $_ -ne '' } | Select-Object -Skip 1)
    if ($wordToComplete -ne '' -and $words.Count -gt 0) {
        $words = @($words | Select-Object -SkipLast 1)
    }

    # The command is the first word that is not a global flag or its value.
    $command = $null
    $rest = @()
    $skip = $false
    foreach ($word in $words) {
        if ($null -ne $command) { $rest += $word; continue }
        if ($skip) { $skip = $false; continue }
        if ($model.GlobalValueFlags -contains $word) { $skip = $true; continue }
        if ($word.StartsWith('-')) { continue }
        $command = $word
    }

    if ($null -eq $command) {
        if ($skip) { return }
        if ($wordToComplete.StartsWith('-')) {
            Get-CospecCompletionResult $model.Globals $wordToComplete 'ParameterName'
        } else {
            Get-CospecCompletionResult $model.Commands $wordToComplete 'ParameterValue'
        }
        return
    }

    $surface = $model.Commands | Where-Object { $_.Name -eq $command } | Select-Object -First 1
    if ($null -eq $surface) { return }

    # A command's first operand may name a subcommand, which then owns the rest.
    $operands = @(Get-CospecOperand $rest $surface.ValueFlags)
    $position = $operands.Count
    $items = @()
    $subcommand = $null
    if ($position -gt 0) {
        $subcommand = $surface.Subcommands | Where-Object { $_.Name -eq $operands[0] } | Select-Object -First 1
    }
    if ($null -ne $subcommand) {
        $surface = $subcommand
        $position = $position - 1
    } elseif ($position -eq 0) {
        $items += @($surface.Subcommands)
    }

    $previous = if ($rest.Count -gt 0) { $rest[$rest.Count - 1] } else { '' }
    if ($surface.ValueFlags -contains $previous) {
        if ($surface.FlagSources.ContainsKey($previous)) {
            Get-CospecCompletionResult (ConvertTo-CospecItem (Get-CospecDynamic $surface.FlagSources[$previous])) $wordToComplete 'ParameterValue'
        }
        return
    }

    if ($wordToComplete.StartsWith('-')) {
        Get-CospecCompletionResult $surface.Flags $wordToComplete 'ParameterName'
        return
    }
    if ($position -gt 0) { return }

    $items += ConvertTo-CospecItem $surface.Choices
    foreach ($source in $surface.Sources) {
        $items += ConvertTo-CospecItem (Get-CospecDynamic $source)
    }
    Get-CospecCompletionResult $items $wordToComplete 'ParameterValue'
}
`
}
