// zsh completion generator. Hand-rolled `compadd`/`_describe` rather than an
// `_arguments` spec: the command table is flat (one subcommand level, a
// pre-formatted flag list, at most one dynamic positional), and a hand-rolled
// function is far easier to keep parseable under `zsh -n`.

import { escapeSingleQuoted } from './bash.ts'
import type { CompletionSpec } from './spec.ts'

/** `_describe` entries are `name:description`, so a literal colon must escape. */
function describeEntry(name: string, summary: string): string {
  return `'${escapeSingleQuoted(name)}:${escapeSingleQuoted(summary.replaceAll(':', String.raw`\:`))}'`
}

function caseArm(name: string, body: string[]): string {
  return [`    ${name})`, ...body.map((line) => `      ${line}`), '      ;;'].join('\n')
}

export function renderZshCompletion(spec: CompletionSpec): string {
  const commands = spec.commands.map((c) => `    ${describeEntry(c.name, c.summary)}`).join('\n')
  const globals = spec.globalFlags.map((f) => `'${escapeSingleQuoted(f)}'`).join(' ')

  const flagArms = spec.commands
    .filter((c) => c.flags.length > 0)
    .map((c) =>
      caseArm(c.name, [`flags=(${c.flags.map((f) => `'${escapeSingleQuoted(f)}'`).join(' ')})`]),
    )
    .join('\n')

  const positionalArms = spec.commands
    .filter((c) => c.positional.length > 0)
    .map((c) =>
      caseArm(
        c.name,
        c.positional.map((source) => `_cospec_dynamic ${source}`),
      ),
    )
    .join('\n')

  const flagValueArms = spec.commands
    .filter((c) => Object.keys(c.flagValues).length > 0)
    .map((c) =>
      caseArm(
        c.name,
        Object.entries(c.flagValues).map(
          (entry) =>
            `[[ $prev == '${escapeSingleQuoted(entry[0])}' ]] && { _cospec_dynamic ${entry[1]}; return }`,
        ),
      ),
    )
    .join('\n')

  return `#compdef cospec
# zsh completion for cospec — generated by 'cospec completion zsh'.
# Install: cospec completion zsh > ~/.zsh/completions/_cospec (dir on $fpath)

_cospec_dynamic() {
  local -a items
  items=(\${(f)"$(cospec __complete $1 2>/dev/null | cut -f1)"})
  (( \${#items} )) && compadd -a items
}

_cospec() {
  local -a commands global_flags flags
  commands=(
${commands}
  )
  global_flags=(${globals})

  local cmd='' prev='' i
  for (( i = 2; i < CURRENT; i++ )); do
    case \${words[i]} in
      -*) ;;
      *) cmd=\${words[i]}; break ;;
    esac
  done
  (( CURRENT > 1 )) && prev=\${words[CURRENT-1]}

  if [[ -z $cmd ]]; then
    _describe -t commands 'cospec command' commands
    compadd -a global_flags
    return
  fi

  case $cmd in
${flagValueArms}
  esac

  if [[ \${words[CURRENT]} == -* ]]; then
    flags=()
    case $cmd in
${flagArms}
    esac
    compadd -a flags
    compadd -a global_flags
    return
  fi

  case $cmd in
${positionalArms}
  esac
}

_cospec "$@"
`
}
