import { stringify } from 'yaml'

/** The three harness targets cospec generates project files for (DESIGN §6.1). */
export type HarnessName = 'claude' | 'codex' | 'opencode'

export const HARNESS_NAMES: readonly HarnessName[] = ['claude', 'codex', 'opencode']

export function isHarnessName(value: string): value is HarnessName {
  return (HARNESS_NAMES as readonly string[]).includes(value)
}

/** A workflow's identity fields, as declared in canon/workflows/harness.yaml. */
export interface WorkflowDef {
  id: string
  command: string
  skill: string
  title: string
  description: string
  injectTypeTable?: boolean
}

/**
 * Codex bodies keep the canonical `/cospec:x` colon spelling (informational — Codex has no
 * slash commands, only skills). OpenCode rewrites it to its `/cospec-x` hyphen spelling so the
 * in-body references match the slash commands OpenCode actually registers. Claude is canonical.
 */
export function transformBodyForHarness(body: string, harness: HarnessName): string {
  if (harness === 'opencode') return body.replaceAll('/cospec:', '/cospec-')
  return body
}

/** SKILL.md frontmatter — identical shape across all three harnesses (DESIGN §6.3). */
export function buildSkillFrontmatter(
  w: WorkflowDef,
  version: string,
  contentHash: string,
): Record<string, unknown> {
  return {
    name: w.skill,
    description: w.description,
    license: 'MIT',
    compatibility: 'Requires the cospec CLI (@aligned-team/conventional-openspec).',
    metadata: provenance(version, contentHash),
  }
}

/** Claude slash-command frontmatter (`.claude/commands/cospec/<name>.md`). */
export function buildClaudeCommandFrontmatter(
  w: WorkflowDef,
  version: string,
  contentHash: string,
): Record<string, unknown> {
  return {
    name: `COSPEC: ${w.title}`,
    description: w.description,
    category: 'Workflow',
    tags: ['cospec', 'workflow'],
    metadata: provenance(version, contentHash),
  }
}

/** OpenCode slash-command frontmatter (`.opencode/commands/cospec-<name>.md`) — minimal. */
export function buildOpencodeCommandFrontmatter(
  w: WorkflowDef,
  version: string,
  contentHash: string,
): Record<string, unknown> {
  return {
    description: w.description,
    metadata: provenance(version, contentHash),
  }
}

function provenance(version: string, contentHash: string): Record<string, unknown> {
  return { author: 'cospec', generatedBy: version, contentHash }
}

/** Serialize a frontmatter object to a YAML block body (no delimiters). Deterministic. */
export function serializeFrontmatter(frontmatter: Record<string, unknown>): string {
  return stringify(frontmatter, { lineWidth: 0 })
}

/**
 * Codex prefix-rule allowlist (`.codex/rules/cospec.rules`, DESIGN §6.1). Pre-approves the
 * read-only and gate commands; `archive` is intentionally omitted (it mutates specs + history).
 */
export function renderCodexRules(version: string): string {
  const allow = [
    ['cospec', 'validate'],
    ['cospec', 'status'],
    ['cospec', 'list'],
    ['cospec', 'instructions'],
    ['cospec', 'apply'],
    ['cospec', 'sync-blockers', '--check'],
    ['cospec', 'new'],
    ['cospec', 'doctor'],
  ]
  const lines = allow.map(
    (pattern) =>
      `prefix_rule(pattern=[${pattern.map((p) => `"${p}"`).join(', ')}], decision="allow")`,
  )
  return [
    `# cospec — pre-approved read-only and gate commands for Codex. Generated by ${version}.`,
    '# Edit cospec canon, not this file. `archive` is intentionally NOT pre-approved.',
    '',
    ...lines,
    '',
  ].join('\n')
}
