import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import { Document, isMap, parse as parseYaml, parseDocument, YAMLMap } from 'yaml'

import { canonFile } from '../canon/embedded.ts'
import {
  classifyManagedMarkdown,
  classifyManifestFile,
  type Manifest,
  type ManagedFrontmatter,
  type ManagedState,
  readManifest,
  renderManaged,
  splitFrontmatter,
} from '../core/managed-files.ts'

// The GitHub Copilot cloud coding-agent files, ported from the pinned binary's
// `core/github-copilot/cloud-agent.js` and spelled for cospec. Provenance is cospec's own:
// the agent file self-describes through its `metadata` block, the frontmatter-less workflow
// through `openspec/.cospec-manifest.json`. A file with neither is never ours to rewrite or
// remove, including OpenSpec's own `openspec.agent.md` and `copilot-setup-steps.yml`.

/** The harness row the cloud files belong to. */
export const COPILOT_HARNESS = 'github-copilot'

export const COPILOT_CLOUD_MARKER = 'Generated by cospec for GitHub Copilot coding agent support.'

export const COPILOT_CLOUD_FILES = {
  setupSteps: '.github/workflows/copilot-setup-steps.yml',
  agent: '.github/agents/cospec.agent.md',
} as const

/** The alternate custom-agent profile name; when present, cospec leaves the profile alone. */
export const COPILOT_AGENT_ALTERNATE_FILE = '.github/agents/cospec.md'

const CLOUD_PATHS: readonly string[] = Object.values(COPILOT_CLOUD_FILES)

export function copilotSetupStepsContent(): string {
  return readFileSync(canonFile('github-copilot/copilot-setup-steps.yml.tpl'), 'utf8')
}

/** The agent file's frontmatter fields and body, before the provenance block is injected. */
export function copilotAgentFrontmatter(): ManagedFrontmatter {
  const { frontmatter, body } = splitFrontmatter(
    readFileSync(canonFile('github-copilot/cospec.agent.md.tpl'), 'utf8'),
  )
  if (frontmatter === undefined) {
    throw new Error('canon/github-copilot/cospec.agent.md.tpl has no parseable frontmatter')
  }
  return { fields: frontmatter, body }
}

/** The agent file as written to disk (provenance injected). */
export function copilotAgentContent(): string {
  return renderManaged(copilotAgentFrontmatter())
}

export type CloudFileState = 'absent' | ManagedState

/**
 * Classify one project-relative path. Only the two cloud files can be `managed` or
 * `modified`; any other existing path (OpenSpec's `openspec.agent.md`, a user's own agent)
 * is `foreign` and never ours.
 */
export function classifyCloudFile(
  cwd: string,
  relPath: string,
  manifest: Manifest | undefined = readManifest(cwd),
): CloudFileState {
  const full = join(cwd, relPath)
  if (!existsSync(full)) return 'absent'
  if (!CLOUD_PATHS.includes(relPath)) return 'foreign'
  const text = readFileSync(full, 'utf8')
  return relPath === COPILOT_CLOUD_FILES.agent
    ? classifyManagedMarkdown(text)
    : classifyManifestFile(text, manifest?.files[relPath])
}

export function classifyCloudFiles(
  cwd: string,
  manifest: Manifest | undefined = readManifest(cwd),
): Record<string, CloudFileState> {
  return Object.fromEntries(CLOUD_PATHS.map((p) => [p, classifyCloudFile(cwd, p, manifest)]))
}

export type AgentReconciliation = 'reconcile' | 'skip' | 'remove-managed'

/**
 * Where the alternate profile (`cospec.md`) and the managed profile (`cospec.agent.md`)
 * meet: no alternate means reconcile; alternate without a profile means skip; alternate
 * with an untouched managed profile means remove the profile; alternate with any other
 * profile is a conflict.
 */
export function classifyCopilotAgentReconciliation(
  cwd: string,
  manifest: Manifest | undefined = readManifest(cwd),
): AgentReconciliation {
  if (!existsSync(join(cwd, COPILOT_AGENT_ALTERNATE_FILE))) return 'reconcile'
  const state = classifyCloudFile(cwd, COPILOT_CLOUD_FILES.agent, manifest)
  if (state === 'absent') return 'skip'
  if (state === 'managed') return 'remove-managed'
  throw new Error(
    `Conflicting Copilot agent profiles: preserve either ${COPILOT_AGENT_ALTERNATE_FILE} or ${COPILOT_CLOUD_FILES.agent}`,
  )
}

/** Throws unless the nearest existing ancestor of `filePath` is a directory. */
export function assertCreatableFilePath(filePath: string): void {
  let candidate = dirname(filePath)
  for (;;) {
    let isDir: boolean | undefined
    try {
      isDir = statSync(candidate).isDirectory()
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    }
    if (isDir === false) throw new Error(`Parent path is not a directory: ${candidate}`)
    if (isDir === true) return
    const parent = dirname(candidate)
    if (parent === candidate) {
      throw new Error(`Cannot resolve a directory ancestor for: ${filePath}`)
    }
    candidate = parent
  }
}

/** Throws when `filePath` exists and is not a regular file. */
export function assertMissingOrRegularFile(filePath: string): void {
  try {
    if (!statSync(filePath).isFile()) {
      throw new Error(`Managed Copilot path is not a regular file: ${filePath}`)
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
}

/** The path guards that run before any cloud file is written. */
export function assertCopilotCloudPaths(cwd: string): void {
  const setupSteps = join(cwd, COPILOT_CLOUD_FILES.setupSteps)
  const agent = join(cwd, COPILOT_CLOUD_FILES.agent)
  assertCreatableFilePath(setupSteps)
  assertCreatableFilePath(agent)
  assertMissingOrRegularFile(setupSteps)
  assertMissingOrRegularFile(agent)
  assertMissingOrRegularFile(join(cwd, COPILOT_AGENT_ALTERNATE_FILE))
}

// ---------------------------------------------------------------------------
// Opt-in in openspec/config.yaml
// ---------------------------------------------------------------------------

export type Warn = (line: string) => void

const warnStderr: Warn = (line) => {
  process.stderr.write(`${line}\n`)
}

/** `config.yaml` first, then `config.yml`; `undefined` when neither exists. */
export function resolveConfigFilePath(cwd: string): string | undefined {
  for (const name of ['config.yaml', 'config.yml']) {
    const path = join(cwd, 'openspec', name)
    if (existsSync(path)) return path
  }
  return undefined
}

const FILE_ACCESS_CODES = new Set(['EACCES', 'EPERM', 'EROFS'])

function firstLine(error: unknown): string {
  return (error instanceof Error ? error.message : String(error)).split('\n')[0]!
}

/**
 * Read the persisted opt-in: `true`, `false`, or `undefined` (never decided, or malformed).
 * A malformed value reads as undecided with the pinned binary's warning sentence.
 */
export function readCopilotCloudOptIn(cwd: string, warn: Warn = warnStderr): boolean | undefined {
  const path = resolveConfigFilePath(cwd)
  if (path === undefined) return undefined
  let raw: unknown
  try {
    raw = parseYaml(readFileSync(path, 'utf8'))
  } catch (error) {
    if (error instanceof Error && error.name.startsWith('YAML')) {
      warn(`Warning: could not parse ${path} (${firstLine(error)}); ignoring it.`)
      return undefined
    }
    throw error
  }
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const section = (raw as Record<string, unknown>).githubCopilot
  if (section === undefined) return undefined
  if (section === null || typeof section !== 'object' || Array.isArray(section)) {
    warn(`Invalid 'githubCopilot' field in config (must be an object)`)
    return undefined
  }
  const value = (section as Record<string, unknown>).cloudAgent
  if (typeof value === 'boolean') return value
  if (value !== undefined) {
    warn(`Invalid 'githubCopilot.cloudAgent' field in config (must be a boolean)`)
  }
  return undefined
}

/**
 * Persist the opt-in through the YAML document model so comments and key order survive.
 * Writes nothing when no config file exists. A config that does not parse is left
 * byte-identical with a warning; an unreadable or unwritable one warns with the code and
 * path. Returns whether the value was written.
 */
export function persistCopilotCloudOptIn(
  cwd: string,
  value: boolean,
  warn: Warn = warnStderr,
): boolean {
  const path = resolveConfigFilePath(cwd)
  if (path === undefined) return false
  try {
    const parsed = parseDocument(readFileSync(path, 'utf8'))
    if (parsed.errors.length > 0) {
      warn(
        `Warning: could not parse ${path} (${firstLine(parsed.errors[0])}); left unchanged, githubCopilot.cloudAgent was not saved.`,
      )
      return false
    }
    // A non-mapping root has no map to set a key on; an empty or comment-only file parses to
    // null contents, which `setIn` fills while keeping the comments.
    const doc = parsed.contents === null || isMap(parsed.contents) ? parsed : new Document()
    const section = doc.getIn(['githubCopilot'], true)
    if (section !== undefined && !isMap(section)) doc.setIn(['githubCopilot'], new YAMLMap())
    doc.setIn(['githubCopilot', 'cloudAgent'], value)
    writeFileSync(path, doc.toString())
    return true
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code
    if (code !== undefined && FILE_ACCESS_CODES.has(code)) {
      warn(`Warning: could not save githubCopilot.cloudAgent to ${path} (${code}).`)
      return false
    }
    throw error
  }
}

// ---------------------------------------------------------------------------
// The decision: write the cloud files this run, and whether to remember it
// ---------------------------------------------------------------------------

export type CopilotCloudTier =
  | 'flag'
  | 'config'
  | 'existing-files'
  | 'prompt'
  | 'undecided'
  | 'not-selected'

export interface CopilotCloudDecision {
  /** The first rule that decided: upstream's tiers 1 to 5, and the branch before tier 1. */
  tier: CopilotCloudTier
  /** Write (or refresh) the two files this run. */
  write: boolean
  /** The value to save as `githubCopilot.cloudAgent`; absent leaves the config untouched. */
  persist?: boolean
  /** An explicit no: any managed file left from an earlier run is removed. */
  optedOut: boolean
  /** Nothing decided and nobody to ask: the receipt says how to opt in. */
  skippedUndecided: boolean
  /** A flag was typed but `github-copilot` is not among the selected tools. */
  ignoredFlag: boolean
}

/** The one sentence the binary prints for a flag that cannot apply. */
export const COPILOT_CLOUD_IGNORED_FLAG =
  '--copilot-cloud/--no-copilot-cloud was ignored because the github-copilot tool was not selected.'

/** The confirm's question: upstream's, naming cospec's agent file. */
export const COPILOT_CLOUD_PROMPT =
  'Set up GitHub Copilot cloud coding-agent files? This is for the GitHub-hosted Copilot coding agent (github.com), not Copilot in your editor. ' +
  `It writes two files: ${COPILOT_CLOUD_FILES.setupSteps} and ${COPILOT_CLOUD_FILES.agent}.`

export interface CopilotCloudTerminal {
  /** stdin is a terminal and neither `CI` nor `OPEN_SPEC_INTERACTIVE=0` says otherwise. */
  interactive: boolean
  /** Ask `question` and return the typed line; `undefined` when stdin ended first. */
  ask(question: string): string | undefined
}

export interface CopilotCloudDecisionInput {
  cwd: string
  /** `github-copilot` is among the selected harnesses. */
  selected: boolean
  /** The last of `--copilot-cloud` / `--no-copilot-cloud` typed, when either was. */
  flag: boolean | undefined
  /** `--harness` (or its upstream spelling `--tools`) was given. */
  harnessGiven: boolean
  json: boolean
  terminal: CopilotCloudTerminal
  warn?: Warn
}

/** Whether a managed (untouched, cospec-written) cloud file is on disk. */
export function hasManagedCloudFiles(
  cwd: string,
  manifest: Manifest | undefined = readManifest(cwd),
): boolean {
  return Object.values(classifyCloudFiles(cwd, manifest)).includes('managed')
}

/**
 * Whether to write the two cloud files, and whether to remember the answer, ported from the
 * binary's `resolveCopilotCloudDecision`. In order: the tool is not selected (a flag is then
 * reported, never applied); a flag; a boolean in config; a managed file on disk; an
 * interactive confirm (default No, only when no tool list and no `--json` was given); skip.
 * Only a flag or an answered confirm persists. Closed stdin answers the confirm No.
 */
export function decideCopilotCloud(input: CopilotCloudDecisionInput): CopilotCloudDecision {
  const { cwd, flag } = input
  if (!input.selected) {
    return {
      tier: 'not-selected',
      write: false,
      optedOut: false,
      skippedUndecided: false,
      ignoredFlag: flag !== undefined,
    }
  }
  if (flag !== undefined) {
    return {
      tier: 'flag',
      write: flag,
      persist: flag,
      optedOut: !flag,
      skippedUndecided: false,
      ignoredFlag: false,
    }
  }
  const persisted = readCopilotCloudOptIn(cwd, input.warn)
  if (persisted !== undefined) {
    return {
      tier: 'config',
      write: persisted,
      optedOut: !persisted,
      skippedUndecided: false,
      ignoredFlag: false,
    }
  }
  if (hasManagedCloudFiles(cwd)) {
    return {
      tier: 'existing-files',
      write: true,
      optedOut: false,
      skippedUndecided: false,
      ignoredFlag: false,
    }
  }
  if (!input.harnessGiven && !input.json && input.terminal.interactive) {
    const reply = input.terminal.ask(COPILOT_CLOUD_PROMPT)?.trim().toLowerCase()
    const answer = reply === 'y' || reply === 'yes'
    return {
      tier: 'prompt',
      write: answer,
      persist: answer,
      optedOut: !answer,
      skippedUndecided: false,
      ignoredFlag: false,
    }
  }
  return {
    tier: 'undecided',
    write: false,
    optedOut: false,
    skippedUndecided: true,
    ignoredFlag: false,
  }
}

/**
 * What `generate()` reports about the two cloud files after a run, as repo-relative paths:
 * the managed files now on disk, the paths it left untouched because a file it did not write
 * is there, the managed files it removed, and the edited ones an opt-out left in place.
 */
export interface CopilotCloudReport {
  present: string[]
  collisions: string[]
  removed: string[]
  leftInPlace: string[]
}

export function emptyCopilotCloudReport(): CopilotCloudReport {
  return { present: [], collisions: [], removed: [], leftInPlace: [] }
}

/**
 * What a run does with the cloud files: `write` emits them, `remove` takes the managed ones
 * away (an edited one stays and is reported), `leave` touches neither. `init` passes the
 * decision's outcome; an `update` passes nothing and `generate()` reads the config and the
 * files itself.
 */
export type CopilotCloudDirective = 'write' | 'remove' | 'leave'

export function copilotCloudDirective(decision: CopilotCloudDecision): CopilotCloudDirective {
  if (decision.write) return 'write'
  return decision.optedOut ? 'remove' : 'leave'
}

/** The receipt lines for one run's cloud outcome (design decision 11). */
export function copilotCloudReceiptLines(
  decision: CopilotCloudDecision,
  report: CopilotCloudReport,
  copilotSucceeded: boolean,
): string[] {
  if (!copilotSucceeded) return []
  const lines: string[] = []
  if (decision.write) {
    if (report.present.length > 0) {
      lines.push(`GitHub Copilot cloud files: ${report.present.join(', ')}`)
    }
    if (report.collisions.length > 0) {
      lines.push(
        `Left your existing ${report.collisions.join(' and ')} untouched — add the cospec install step by hand so the Copilot cloud agent can run cospec.`,
      )
    }
  } else if (decision.optedOut) {
    if (report.removed.length > 0) {
      lines.push(
        `Removed: ${report.removed.length} Copilot cloud agent file(s) (opted out of cloud files)`,
      )
    }
    for (const path of report.leftInPlace) {
      lines.push(`Left ${path} in place: edited since cospec wrote it (opted out of cloud files).`)
    }
  } else if (decision.skippedUndecided) {
    lines.push(
      "Skipped GitHub Copilot cloud files (opt-in). Enable with 'cospec init --copilot-cloud'.",
    )
  }
  return lines
}

/**
 * Whether `github-copilot` was set up this run: selected, and none of its files failed. Every
 * path the row writes is under `.github`, which no other row shares.
 */
export function copilotSucceeded(
  harnesses: readonly string[],
  failedPaths: readonly string[],
): boolean {
  return harnesses.includes(COPILOT_HARNESS) && !failedPaths.some((p) => p.startsWith('.github/'))
}
