import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import { Document, isMap, parse as parseYaml, parseDocument, YAMLMap } from 'yaml'

import { canonFile } from '../canon/embedded.ts'
import {
  classifyManagedMarkdown,
  classifyManifestFile,
  type Manifest,
  type ManagedFrontmatter,
  type ManagedState,
  readManifest,
  renderManaged,
  splitFrontmatter,
} from '../core/managed-files.ts'

// The GitHub Copilot cloud coding-agent files, ported from the pinned binary's
// `core/github-copilot/cloud-agent.js` and spelled for cospec. Provenance is cospec's own:
// the agent file self-describes through its `metadata` block, the frontmatter-less workflow
// through `openspec/.cospec-manifest.json`. A file with neither is never ours to rewrite or
// remove, including OpenSpec's own `openspec.agent.md` and `copilot-setup-steps.yml`.

export const COPILOT_CLOUD_MARKER = 'Generated by cospec for GitHub Copilot coding agent support.'

export const COPILOT_CLOUD_FILES = {
  setupSteps: '.github/workflows/copilot-setup-steps.yml',
  agent: '.github/agents/cospec.agent.md',
} as const

/** The alternate custom-agent profile name; when present, cospec leaves the profile alone. */
export const COPILOT_AGENT_ALTERNATE_FILE = '.github/agents/cospec.md'

const CLOUD_PATHS: readonly string[] = Object.values(COPILOT_CLOUD_FILES)

export function copilotSetupStepsContent(): string {
  return readFileSync(canonFile('github-copilot/copilot-setup-steps.yml.tpl'), 'utf8')
}

/** The agent file's frontmatter fields and body, before the provenance block is injected. */
export function copilotAgentFrontmatter(): ManagedFrontmatter {
  const { frontmatter, body } = splitFrontmatter(
    readFileSync(canonFile('github-copilot/cospec.agent.md.tpl'), 'utf8'),
  )
  if (frontmatter === undefined) {
    throw new Error('canon/github-copilot/cospec.agent.md.tpl has no parseable frontmatter')
  }
  return { fields: frontmatter, body }
}

/** The agent file as written to disk (provenance injected). */
export function copilotAgentContent(): string {
  return renderManaged(copilotAgentFrontmatter())
}

export type CloudFileState = 'absent' | ManagedState

/**
 * Classify one project-relative path. Only the two cloud files can be `managed` or
 * `modified`; any other existing path (OpenSpec's `openspec.agent.md`, a user's own agent)
 * is `foreign` and never ours.
 */
export function classifyCloudFile(
  cwd: string,
  relPath: string,
  manifest: Manifest | undefined = readManifest(cwd),
): CloudFileState {
  const full = join(cwd, relPath)
  if (!existsSync(full)) return 'absent'
  if (!CLOUD_PATHS.includes(relPath)) return 'foreign'
  const text = readFileSync(full, 'utf8')
  return relPath === COPILOT_CLOUD_FILES.agent
    ? classifyManagedMarkdown(text)
    : classifyManifestFile(text, manifest?.files[relPath])
}

export function classifyCloudFiles(
  cwd: string,
  manifest: Manifest | undefined = readManifest(cwd),
): Record<string, CloudFileState> {
  return Object.fromEntries(CLOUD_PATHS.map((p) => [p, classifyCloudFile(cwd, p, manifest)]))
}

export type AgentReconciliation = 'reconcile' | 'skip' | 'remove-managed'

/**
 * Where the alternate profile (`cospec.md`) and the managed profile (`cospec.agent.md`)
 * meet: no alternate means reconcile; alternate without a profile means skip; alternate
 * with an untouched managed profile means remove the profile; alternate with any other
 * profile is a conflict.
 */
export function classifyCopilotAgentReconciliation(
  cwd: string,
  manifest: Manifest | undefined = readManifest(cwd),
): AgentReconciliation {
  if (!existsSync(join(cwd, COPILOT_AGENT_ALTERNATE_FILE))) return 'reconcile'
  const state = classifyCloudFile(cwd, COPILOT_CLOUD_FILES.agent, manifest)
  if (state === 'absent') return 'skip'
  if (state === 'managed') return 'remove-managed'
  throw new Error(
    `Conflicting Copilot agent profiles: preserve either ${COPILOT_AGENT_ALTERNATE_FILE} or ${COPILOT_CLOUD_FILES.agent}`,
  )
}

/** Throws unless the nearest existing ancestor of `filePath` is a directory. */
export function assertCreatableFilePath(filePath: string): void {
  let candidate = dirname(filePath)
  for (;;) {
    let isDir: boolean | undefined
    try {
      isDir = statSync(candidate).isDirectory()
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
    }
    if (isDir === false) throw new Error(`Parent path is not a directory: ${candidate}`)
    if (isDir === true) return
    const parent = dirname(candidate)
    if (parent === candidate) {
      throw new Error(`Cannot resolve a directory ancestor for: ${filePath}`)
    }
    candidate = parent
  }
}

/** Throws when `filePath` exists and is not a regular file. */
export function assertMissingOrRegularFile(filePath: string): void {
  try {
    if (!statSync(filePath).isFile()) {
      throw new Error(`Managed Copilot path is not a regular file: ${filePath}`)
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
}

/** The path guards that run before any cloud file is written. */
export function assertCopilotCloudPaths(cwd: string): void {
  const setupSteps = join(cwd, COPILOT_CLOUD_FILES.setupSteps)
  const agent = join(cwd, COPILOT_CLOUD_FILES.agent)
  assertCreatableFilePath(setupSteps)
  assertCreatableFilePath(agent)
  assertMissingOrRegularFile(setupSteps)
  assertMissingOrRegularFile(agent)
  assertMissingOrRegularFile(join(cwd, COPILOT_AGENT_ALTERNATE_FILE))
}

// ---------------------------------------------------------------------------
// Opt-in in openspec/config.yaml
// ---------------------------------------------------------------------------

export type Warn = (line: string) => void

const warnStderr: Warn = (line) => {
  process.stderr.write(`${line}\n`)
}

/** `config.yaml` first, then `config.yml`; `undefined` when neither exists. */
export function resolveConfigFilePath(cwd: string): string | undefined {
  for (const name of ['config.yaml', 'config.yml']) {
    const path = join(cwd, 'openspec', name)
    if (existsSync(path)) return path
  }
  return undefined
}

const FILE_ACCESS_CODES = new Set(['EACCES', 'EPERM', 'EROFS'])

function firstLine(error: unknown): string {
  return (error instanceof Error ? error.message : String(error)).split('\n')[0]!
}

/**
 * Read the persisted opt-in: `true`, `false`, or `undefined` (never decided, or malformed).
 * A malformed value reads as undecided with the pinned binary's warning sentence.
 */
export function readCopilotCloudOptIn(cwd: string, warn: Warn = warnStderr): boolean | undefined {
  const path = resolveConfigFilePath(cwd)
  if (path === undefined) return undefined
  let raw: unknown
  try {
    raw = parseYaml(readFileSync(path, 'utf8'))
  } catch (error) {
    if (error instanceof Error && error.name.startsWith('YAML')) {
      warn(`Warning: could not parse ${path} (${firstLine(error)}); ignoring it.`)
      return undefined
    }
    throw error
  }
  if (raw === null || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const section = (raw as Record<string, unknown>).githubCopilot
  if (section === undefined) return undefined
  if (section === null || typeof section !== 'object' || Array.isArray(section)) {
    warn(`Invalid 'githubCopilot' field in config (must be an object)`)
    return undefined
  }
  const value = (section as Record<string, unknown>).cloudAgent
  if (typeof value === 'boolean') return value
  if (value !== undefined) {
    warn(`Invalid 'githubCopilot.cloudAgent' field in config (must be a boolean)`)
  }
  return undefined
}

/**
 * Persist the opt-in through the YAML document model so comments and key order survive.
 * Writes nothing when no config file exists. A config that does not parse is left
 * byte-identical with a warning; an unreadable or unwritable one warns with the code and
 * path. Returns whether the value was written.
 */
export function persistCopilotCloudOptIn(
  cwd: string,
  value: boolean,
  warn: Warn = warnStderr,
): boolean {
  const path = resolveConfigFilePath(cwd)
  if (path === undefined) return false
  try {
    const parsed = parseDocument(readFileSync(path, 'utf8'))
    if (parsed.errors.length > 0) {
      warn(
        `Warning: could not parse ${path} (${firstLine(parsed.errors[0])}); left unchanged, githubCopilot.cloudAgent was not saved.`,
      )
      return false
    }
    // A non-mapping root has no map to set a key on; an empty or comment-only file parses to
    // null contents, which `setIn` fills while keeping the comments.
    const doc = parsed.contents === null || isMap(parsed.contents) ? parsed : new Document()
    const section = doc.getIn(['githubCopilot'], true)
    if (section !== undefined && !isMap(section)) doc.setIn(['githubCopilot'], new YAMLMap())
    doc.setIn(['githubCopilot', 'cloudAgent'], value)
    writeFileSync(path, doc.toString())
    return true
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code
    if (code !== undefined && FILE_ACCESS_CODES.has(code)) {
      warn(`Warning: could not save githubCopilot.cloudAgent to ${path} (${code}).`)
      return false
    }
    throw error
  }
}
